;-----------------------------------
[Bastion of Thunder - (Mob)]
Mob1=a jord profet
Mob2=a jord militis
Mob3=a jord kjal
Mob4=a jord tyv
Mob5=a jord far
Mob6=a jord skygge
Mob7=a jord kriger
;-----------------------------------
[Bastion of Thunder - (Loc)]
Loc1= -206.83 19.36 -1543.50
Loc2= -490.00 -66.00 -1524.00
;-----------------------------------
[Dulak's Harbor - (Mob)]
Mob1=a fisherman
Mob2=a fish gutter
Mob3=a lead engineer
Mob4=an engineering assistant
;-----------------------------------
[Dulak's Harbor - (Loc)]
Loc1= 490.00 329.00 3.12
Loc2= 307.00 255.00 3.75
Loc3= 343.46 398.49 3.12
Loc4= 215.00 177.00 3.12
Loc4= 200.00 323.00 3.12
;-----------------------------------
[Wall of Slaughter - (Mob)]
Mob1=a raging chimera
Mob2=an elite kyv hunter
Mob3=an elite noc cleaver
Mob4=an elite noc sprayblood
Mob5=an elite ukun deathfang
Mob6=an infernal chimera
Mob7=Kyv Pureshot
Mob8=Ukun Fleshflayer
;-----------------------------------
[Wall of Slaughter - (Loc)]
Loc1=1271.00 1353.00 125.37
;-----------------------------------
[Muramite Proving Grounds - (Mob)]
Mob1=a discordling enchainer
Mob2=a discordling taskfiend
Mob3=an elite ukun deathfang
Mob4=an elite aneuk darkdiviner
Mob5=an elite aneuk fleshthreader
Mob6=an elite ikaav binder
Mob7=an elite ikaav detainer
;-----------------------------------
[Muramite Proving Grounds - (Loc)]
Loc1=
;-----------------------------------
[Riftseekers' Sanctum - (Mob)]
Mob1=a gelidran deathfreeze
Mob2=a gelidran flamefreeze
Mob3=a gelidran frostblade
Mob4=a gelidran frostmaster
Mob5=a gelidran guard
Mob6=a gelidran hailbringer
Mob7=a gelidran icedagger
Mob8=a gelidran iceshadow
Mob9=a gelidran iceskin
Mob10=a gelidran icespinner
Mob11=a gelidran researcher
Mob12=a pyrilen cinderhealer
Mob13=a pyrilen fireblade
Mob14=a pyrilen firecharmer
Mob15=a pyrilen flamedouser
Mob16=a pyrilen flamemistress
Mob17=a pyrilen flameshard
Mob18=a pyrilen guard
Mob19=a pyrilen sirenscorcher
Mob20=a pyrilen slayfire
Mob21=a pyrilen spinesinge
;-----------------------------------
[Riftseekers' Sanctum - (Loc)]
Loc1=720.12 169.87 -229.84
Loc2=738.00 74.00 -229.84
Loc3=713.00 -168.00 -229.84
Loc4=420.97 -396.80 -230.64
Loc5=-42.62 -247.17 -234.00
Loc6=-134.00 -48.00 -236.50
Loc7=-138.25 57.50 -229.84
Loc8=-38.00 254.00 -229.84
Loc9=42.00 336.00 -232.00
Loc10=139.87 411.12 -236.75
Loc11=233.00 439.00 -232.00
Loc12=477.12 318.62 -236.75
Loc13=591.25 324.50 -236.62
;Loc14=768.29 478.22 -233.88
;-----------------------------------
[Dranik's Hollows - (Mob)]
Mob1=a Shrewd Dragorn
Mob2=a blighted cave rat
;-----------------------------------
[Dranik's Hollows - (Loc)]
Loc1=614.00 1619.00 62.12
;-----------------------------------
[Sewers of Dranik - (Mob)]
Mob1=a Cunning Dragorn
Mob2=a subjugated stoneworker
Mob3=a twisted stoneworker
Mob4=an elite ukun bloodbeast
Mob5=An Elite Ukun Bloodhowler
;-----------------------------------
[Sewers of Dranik - (Loc)]
Loc1=1210.73 -937.06 -20.62
;-----------------------------------
[Catacombs of Dranik - (Mob)]
Mob1=Insidious Dragorn
Mob2=a noc scout
;-----------------------------------
[Catacombs of Dranik - (Loc)]
Loc1=1140.00 -85.00 -111.37
;-----------------------------------
[The Crypt of Nadox - (Mob)]
Mob1=a shrine bruiser
Mob2=a treasure sorter
Mob3=a luggald abomination
Mob4=a luggald chosen
Mob5=a luggald guardian
Mob6=a luggald initiate
Mob7=a luggald overseer
Mob8=an incubator operator
Mob9=a treasure sorter
Mob10=a furious Blackhand
Mob11=a vehement Blackhand
Mob12=a Blackhand lieutenant
;-----------------------------------
[The Crypt of Nadox - (Loc)]
Loc1=268.00 817.00 -23.36
Loc2=222.00 1271.00 -23.36
Loc3=-377.00 1284.00 -23.12
Loc4=-297.00 881.00 -23.37
;-----------------------------------
[Crushbone: Hardcore - (Loc)]
Loc1=-145.00 402.00 3.75
Loc2=-103.00 358.00 3.75
Loc3=-282.00 349.00 3.75
Loc4=-258.00 308.00 2.82
Loc5=-392.12 292.12 3.75
Loc6=-418.00 227.00 3.75
Loc7=-613.00 266.00 3.75
Loc8=-616.00 215.00 3.75
Loc9=-574.00 213.00 2.82
Loc10=-522.00 440.00 3.75
Loc11=-472.00 438.00 3.75
Loc12=-507.00 559.00 3.75
Loc13=-489.00 582.00 3.75
Loc14=-334.00 508.00 3.75
Loc15=-224.00 558.00 3.75
Loc16=-242.00 604.00 15.82
Loc17=-144.00 732.00 -25.88
Loc18=-153.00 643.00 -27.25
Loc19=-103.00 664.00 -27.25
Loc20=1.00 526.00 -9.18
Loc21=66.00 576.00 -20.88
Loc22=96.00 596.00 -19.88
Loc23=146.25 524.12 -21.62
Loc24=-386.62 362.25 0.63
Loc25=242.00 416.00 2.00
Loc26=202.00 391.00 4.00
Loc27=260.00 373.00 4.00
;-----------------------------------