|****************************************************************************************************************
e3Hunter.mac - by Kroaking
Last Updated: April 2nd, 2026 - 05:48:00 PM

v1.3.7

****************************************************************************************************************|
/squelch /log on
#chat group

#Event CantSee "You cannot see your target."
#Event TooFar  "Your target is #*#, get closer!"
#Event CantHit "You can't hit them from here."

#Event BagsFull "#*#There was no place to put that#*#"#Event BagsFull "#*#There was no place to put that#*#"
#Event BagsFull "#*#There are no open slots for the held item in your inventory#*#"

#Event LoreItem "#*#You cannot loot this Lore Item.#*#"

#Event GotExp 	"#*#You have gained (#*#) party experience! (#1#)#*#"

#event NavMeshReload "#*#Could not locate destination on navmesh#*#"

#event TurboLootDone "#*# tells the group, '[DONE LOOTING]'#*#"

#define /message "/echo \ay[\atE3Hunter\ay]\aw "

| --------------------------------------------------------------------------------------------
Sub Main
	/if (${Debugging}) /echo Sub Main Entry

	/declare StuckSpamTimerSet	timer		outer	0
	/declare StuckSpamTrigger	timer		outer	0
	/declare OutX1 				int 		outer 	${Me.X}
	/declare OutY1 				int 		outer	${Me.Y}
	/declare OutZ1				int			outer	${Me.Z}
	/declare StuckCountOut 		int 		outer	0
	/declare BackUpTimer		int			outer 	0
	/declare GroupWaitTimer		int			outer	0
	/declare StuckSwitch		int 		outer
	/declare runcounter 		int 		outer	0
	/declare notkillable		int 		outer	0
	/declare Announce			bool		outer	FALSE
	/declare version			string		outer	1.3.7
	/declare LastUpdated		string		outer	"Last Updated: April 2nd, 2026 - 05:48:00 PM"

	/message ==================================================================
 	/call Declares
	/message ==================================================================
	/message \at${MacroName}.mac \aw- \atv${version} \awby \ag Kroaking
	/message \at${LastUpdated}.
	/message ==================================================================
	/delay 2s

	|---------------------------------------------------------------------------
	/message \ayVALID \aghunting Methods are\ao: \am[\atLOC \ao| \atMOB | \atANY\am]\ax
	|---------------------------------------------------------------------------

	|---------------------------------------------------------------------------
	/if (${HuntMethod.Equal[LOC]})  {
		/message \at***\at \agHuntMethod: \ayis currently set to \at[\ag${HuntMethod}\at] \at***\at\ar.
		/message ==================================================================
		/message \at***\at \ayHuntMethod specific settings\ao: \at***\at\ar.
		/message \am- LastLoc_Zone \ayis set to \at[\ag${LastLoc_Zone}\at]\ax
		/message \am- LastLoc_Step \ayis set to \at[\ag${LastLoc_Step}\at]\ax
	}
	/message ==================================================================
		
	|---------------------------------------------------------------------------
	/if (${HuntMethod.Equal[MOB]}) {
		/message \at***\at \agHuntMethod: \ayis currently set to \at[\ao${HuntMethod}\at] \at***\at\ar.
		/message ==================================================================
		/message \at***\at \ayHuntMethod specific settings\ao: \at***\at\ar.
		/message \ag- RV_CampRadius \ayis set to \at[\ag${RV_CampRadius}\at]\ax
		/message \ag- RV_FailMax \ayis set to \at[\ag${RV_FailMax}\at]\ax
		/message \ag- RV_GetMobAtFullHealth \ayis set to \at[\ag${RV_GetMobAtFullHealth}\at]\ax
		/message \ag- RV_MaxZRange \ayis set to \at[\ag${RV_MaxZRange}\at]\ax
		/message \ag- RV_MinZRange \ayis set to \at[\ag${RV_MinZRange}\at]\ax
		/message \ag- RV_Range \ayis set to \at[\ag${RV_Range}\at]\ax
		/message \ag- RV_SpawnRecheckTimer \ayis set to \at[\ag${RV_SpawnRecheckTimer}\at]\ax
		/message \ag- RV_StepValue \ayis set to \at[\ag${RV_StepValue}\at]\ax
		/message \ag- RV_ZRadius \ayis set to \at[\ag${RV_ZRadius}\at]\ax	
	}
	|---------------------------------------------------------------------------
	
	|---------------------------------------------------------------------------
	/if (${HuntMethod.Equal[ANY]}) {
		/message \at***\at \agHuntMethod: \ayis currently set to \at[\ar${HuntMethod}\at] \at***\at\ar
		/message ==================================================================
		/message \at***\at \ayHuntMethod specific settings\ao: \at***\at\ar.
		/message \ag- RV_CampRadius \ayis set to \at[\ag${RV_CampRadius}\at]\ax	
	}
	|---------------------------------------------------------------------------	
	/message ==================================================================
	/delay 3s
	
	|----------------
	/call CheckThings
	|----------------
	
	|--------------------------------------------
	/if (${MouseLock}) {
		/message \ag- MouseLock \ayis set to \am[\at${MouseLock}\am]\ax
		/message \ag- MouseLock \aoCoordinates: \am[\atX=${MouseLocValX}, Y=${MouseLocValY}\am]\ax
		/mouseto ${MouseLocValX}, ${MouseLocValY}
	}
	|--------------------------------------------			
	
	|-------------------------------------------------------------	
	/if ((${GrpHasENCClass} || ${GrpHasWIZClass}) && ${DoPBAOE}) {
		/message ==================================================================
		/message \ar ~ NOTE: \aoWe have \ayPBAE\ao classe(s) in group and \am[\atDoPBAOE\am]\ao is currently \am[\ar${DoPBAOE}\am]\ao.
		/message \ay ~ PBAE Mob count threshhold is currently at\ao: \am[\at${PBAOE_MobCount}\am]\ax
		/message ==================================================================	
		/delay 2s
	}
	|-------------------------------------------------------------	
	/message \agGetting things ready, sit back...
	/delay 2s

	/message \ayI am currently in \am[\at${Zone.Name}\am]\ay.\ax
	|--------------
	/call GroupWait
	|--------------
	
	
	
	
	
	
	|-------
	|--/end
	|-------
	
	
	
	
	
	| --- MAIN ------------------------------------------------------------------------------
	:mainloop
	|---------
	/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) /call DoClearTargets
	|---------	
	
	/message ==================================================================
	/message \aw<\ar*\ao*\ay*\ag*\at*\au*\am*\ap*\aw> \ayABOUT TO PULL VIA METHOD: \at(\ar${HuntMethod}\at)\ay . . . get ready! \aw<\ap*\am*\au*\at*\ag*\ay*\ao*\ar*\aw>
	/popcustom 13 5 ---> ABOUT TO PULL VIA METHOD: (${HuntMethod}) . . . get ready! <---
	
	|----------------------------------------------
	|--- Set My CampLoc
	|----------------------------------------------
	/varset CampReturnLoc	${Me.Y} ${Me.X} ${Me.Z}
	/message                 \agSetting Camp Location to: \am(\arY\ao:\at${Me.Y} \arX\ao:\at${Me.X} \arZ\ao:\at${Me.Z}\am)\ax
	/message ==================================================================
	/delay 3s
	|----------------------------------------------
	
	|----------------------------
	| ENGINE SELECT -- START
	|----------------------------
	|-------------------------While Not Dead 
	/while (!${Me.State.Equal[DEAD]} && (${Zone.ID}==${startZone})) {
		/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) /call DoClearTargets
		/if (${Target.ID} && !${Me.XTarget} && !${Me.Casting.ID}) /squelch /target clear
		|-----------------------------------------------
		| Before we single pull ...   Check if we should loot Corpses.
		|-----------------------------------------------
		/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
		|-----------------------------------------------
		/if (${HuntMethod.Equal[LOC]}) /call DoLocPull
		/if (${HuntMethod.Equal[ANY]}) {
			/varset PullRange ${CampRadius}
			/call DoSinglePull_Any
		}
		/if (${HuntMethod.Equal[MOB]}) {
			/varset RV_MaxRadius ${RV_Range}
			/call DoSinglePull_Name
		}
		/if (${Me.XTarget}) /Call DoClearTargets
		/call GMCheck
		/doevents
	}
	|-------------------------While Not Dead 
	|----------------------------
	| ENGINE SELECT -- END
	|----------------------------

	/doevents
	/delay 1s
	/goto :mainloop
	| --- MAIN ------------------------------------------------------------------------------

	/if (${Debugging}) /echo Sub Main Exit

/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Declares
| --------------------------------------------------------------------------------------------
Sub Declares
	/if (${Debugging}) /echo Sub Declares Entry
	/declare FarmMob 			string outer
	/declare PullRange 			int outer

	|==================== DO NOT ALTER THESE VALUES ====================
	/declare MacroName			string	outer	e3Hunter
	/declare IniFileName		string	outer	${MacroName}_${Me.CleanName}.ini
	/declare ZoneDataFileName	string	outer	${MacroName}_ZoneData.ini
	/declare FirstRun			int		outer	0

	|--------------------------------------
	/if (!${Ini[${IniFileName}].Length}) /varset FirstRun 1
	|--------------------------------------

	/message \ay${IniFileName} is the INI being used.
	/declare BagsAreFull		bool 	outer FALSE
	/declare CampReturnLoc		string	outer NULL
	/declare CampX 				int 	outer ${Me.X}
	/declare CampY 				int 	outer ${Me.Y}
	/declare CampZ 				int 	outer ${Me.Z}
	/declare DebugRepeatTimer 	timer 	outer 1s
	/declare DoGroupGankNoDrop	bool 	outer FALSE
	/declare Endmac 			bool 	outer FALSE
	/declare NoDropMobItem		string	outer	NULL
	/declare PBAE_State			bool	outer FALSE
	/declare SitDelay 			timer 	outer 5s
	/declare Targets 			string 	outer
	/declare TurboLootPause		bool	outer FALSE
	/declare ValidZoneName 		string 	outer ${Zone.Name}
	/declare courseCorrection 	timer 	outer 1s
	/declare myTargetID 		int 	outer 0
	/declare reportTarget 		timer 	outer 5s
	/declare startZone 			int 	outer ${Zone.ID}

	|** SPECIFIC of E3Hunter.mac/SwarmPull declares **|
	|----------------------------------------------------------
	/declare ZoneCount				int		outer 	0
	|----------------------------------------------------------

	|----------------------------------------------------------
	/declare CurrentDC				int		outer	0
	/declare CurrentDCAC			int		outer	0
	|----------------------------------------------------------
	|** SPECIFIC of E3Hunter.mac/SwarmPull declares **|

	|** Declare colors their escape code for read-ability **|
	/declare Black 			string outer \ab
	/declare Blue   		string outer \au
	/declare Brown      	string outer \a-o
	/declare Cyan   		string outer \at
	/declare Gray			string outer \a-w
	/declare Green			string outer \ag
	/declare Pink   		string outer \am
	/declare Orange   		string outer \ao
	/declare Purple   		string outer \ap
	/declare Red   			string outer \ar
	/declare Teal   		string outer \at
	/declare White   		string outer \aw
	/declare Yellow  		string outer \ay
	/declare DarkGreen 		string outer \a-g
	/declare DarkMarroon	string outer \a-m
	/declare DarkPurple		string outer \a-p
	/declare DarkRed		string outer \a-r
	/declare DarkCyan		string outer \a-t
	/declare DarkBlue		string outer \a-u
	/declare DarkYellow		string outer \a-y
	|** End color declarations **|

	|** Start of E3Hunter.mac/PullFarm.mac type declares **|
	/call CheckINI ${IniFileName} General AssistMe bool TRUE
	/call CheckINI ${IniFileName} General CheckBots bool TRUE
	/call CheckINI ${IniFileName} General Debugging bool TRUE
	/call CheckINI ${IniFileName} General DoBurns bool FALSE
	/call CheckINI ${IniFileName} General DoPBAOE bool FALSE
	/call CheckINI ${IniFileName} General GroupNavToMe bool TRUE
	/call CheckINI ${IniFileName} General HuntMethod string MOB
	/call CheckINI ${IniFileName} General LootCorpse bool FALSE
	/call CheckINI ${IniFileName} General LootMethod string DCONLY
	/call CheckINI ${IniFileName} General MinItemValue int 10
	/call CheckINI ${IniFileName} General MouseLock bool TRUE
	/call CheckINI ${IniFileName} General MouseLocValX int 290
	/call CheckINI ${IniFileName} General MouseLocValY int 550
	/call CheckINI ${IniFileName} General NoDropGankItems string NULL
	/call CheckINI ${IniFileName} General PBAOE_MobCount int 5
	/call CheckINI ${IniFileName} General ReclaimDC bool FALSE
	/call CheckINI ${IniFileName} General UseClickBuffs bool FALSE
	/call CheckINI ${IniFileName} General UseClickDamage bool FALSE
	
	/call CheckINI ${IniFileName} Camp RV_CampRadius int 2500
	/call CheckINI ${IniFileName} Camp RV_GetMobAtFullHealth int 1
	/call CheckINI ${IniFileName} Camp RV_Range int 250
	/call CheckINI ${IniFileName} Camp RV_ZRadius int 500
	/call CheckINI ${IniFileName} Camp RV_MinZRange int -50
	/call CheckINI ${IniFileName} Camp RV_MaxZRange int 50
	/call CheckINI ${IniFileName} Camp RV_FailMax int 3
	/call CheckINI ${IniFileName} Camp RV_StepValue int 25
	/call CheckINI ${IniFileName} Camp RV_SpawnRecheckTimer int 60

	/call CheckINI ${IniFileName} Pull PullAbility string ReplaceMeWithYourSkill
	/call CheckINI ${IniFileName} Pull PullAbilityRange int 30
	/call CheckINI ${IniFileName} Pull PullRequiresLineOfSight bool TRUE
	/call CheckINI ${IniFileName} Pull UseCastSpells bool FALSE

	/call CheckINI ${IniFileName} Endurance MedEndAt int 8
	/call CheckINI ${IniFileName} Endurance MedEndTill int 100

	/call CheckINI ${IniFileName} Mana MedAt int 30
	/call CheckINI ${IniFileName} Mana MedTill int 100
	/call CheckINI ${IniFileName} Mana BardMed bool TRUE

	/call CheckINI ${IniFileName} Alerts AFKGM bool TRUE
	/call CheckINI ${IniFileName} Alerts UseBeep bool TRUE

	/call CheckIni ${IniFileName} Zone LastLoc_Zone string NONE
	/call CheckIni ${IniFileName} Zone LastLoc_Step string 1
	/call CheckIni ${IniFileName} Zone LastGankLoot_Member string 0
	|** End of E3Hunter.mac/PullFarm.mac type declares **|	
	
	|------------------------------------------------------------------------------------------------------------
	| Set Turbolooter to the pulled variablie from Mq2Mono Query.
	|------------------------------------------------------------------------------------------------------------
	/declare TurboLooter	string	outer	${MQ2Mono.Query[e3,E3Bots(${Me.CleanName}).Query(GrpMainLooterName)]}
	|------------------------------------------------------------------------------------------------------------
	
	|==================== DO NOT ALTER THESE VALUES ====================
	|------------------------------------------------------------
	|Variables that you don't need to worry about.
	|------------------------------------------------------------
	/declare RV_FailCounter      			int outer  0
	/declare RV_MyTargetID       			int outer  0
	/declare RV_MyTargetName     			string outer
	/declare RV_MyTargetDead     			int outer  0
	/declare RV_InvalidTargetID  			int outer  0
	/declare RV_HasTarget        			int outer  0
	/declare RV_RandomWait       			int outer  0
	/declare RV_LootSlot         			int outer  0
	/declare RV_CheckLook        			int outer  0
	/declare RV_Fighting         			int outer  0
	/declare RV_TargetDead       			int outer  0
	/declare RV_MyXLOC           			int outer  0
	/declare RV_MyYLOC           			int outer  0
	/declare RV_FastRange        			int outer
	/declare RV_RangeMax         			int outer
	/declare RV_RangeMin         			int outer
	/declare RV_MaxRadius         			int outer
	/varcalc RV_FastRange ${RV_Range}+3
	/varcalc RV_RangeMax ${RV_Range}+1
	/varcalc RV_RangeMin ${RV_Range}-1   
	
	/declare anchorY  			int  	outer ${Me.Y}
	/declare anchorX  			int  	outer ${Me.X}
	/declare MyHeading	        int    	outer ${Me.Heading.DegreesCCW}
	/declare StartZoneFullName	string 	outer ${Zone.Name}
	/declare MyClassType 		string 	outer
	/declare MyClassTypePet 	int    	outer 0
	/declare ItemTo 			string 	outer
	/declare StartingPlat 		int    	outer ${Me.Platinum}
	/declare PlatSession 		int    	outer 0  
	
	|------------------------------------------------------------ 
	/declare InAGroup 			bool   	outer 0 FALSE
	/declare E3Detected			string 	outer NULL
	|------------------------------------------------------------   
	|==================== DO NOT ALTER THESE VALUES ====================
	
	|-------------------------------
	/if (${FirstRun}) {
		/message \ayCreated INI file \am[\at${IniFileName}\am]\ay with default values.\ax
		/message \ayPlease edit the file and restart \at${MacroName}.mac\ay.\ax
		/message \arEnding Macro !\ax
		/end
	} else {
		/message \ayConfig loaded from \am[\at${IniFileName}\am]\ay.\ax
	}
	|-------------------------------

	/if (${Debugging}) /echo Sub Declares Exit

/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoClearTargets
| --------------------------------------------------------------------------------------------
Sub DoClearTargets
	/if (${Debugging}) /echo Sub DoClearTargets Entry
	
	/declare i 				int 	local	0
	/declare CurrentTarget 	int 	local	0

	|--------------------------------------------------
	/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]} || (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive})) {
		/ClearTarget usemytarget
		|/keypress esc
		/delay 5
		
		:gotoloopkeepfighting
		|------------------------
		/if (${Me.Sitting} || ${Me.Feigning}) /stand
		|------------------------
		
		|--------------------------------------------------------------------------------------------------
		|-- Call PBAE_Enabled state detection if we have classe(s) and ${DoPBAOE}
		|--------------------------------------------------------------------------------------------------
		/if ((${GrpHasENCClass} || ${GrpHasWIZClass}) && ${DoPBAOE}) {
			|-------------------------------------
			/if (!${PBAE_State} && ${Target.ID} && ${Debugging}) {
				|-- Degub Condition
				/message ==================================================================
				/message \ayPBAE_DEBUGGER\ax
				/message \aoPBAE_State\ay=\am(\ag${PBAE_State}\am)\ao | \aoTargetID\ay=\am(\ag${Target.ID}\am)\ao | \aoTargetDistance\ay=\am(\ag${Target.Distance}\am)\ax
				/message \aoSpawnCount\ay=\am(\ag${SpawnCount[npc radius 25]}\am)\ao | \aoPBAOE_MobCount\ay=\am(\ag${PBAOE_MobCount}\am)\ao | \aoAggressive\ay=\am(\ag${Bool[${Spawn[npc radius 25].Aggressive}]}\am)\ax
				/message ==================================================================
			}
			|-------------------------------------
			/call CheckPBAELogic
		}
		|--------------------------------------------------------------------------------------------------
		
		|------------------------------
		|-- Dont have target, but aggressive mob near.
		|------------------------------
		/if (!${Target.ID} && ${Bool[${Spawn[npc radius 35].Aggressive}]}) {			
			|-----
			/if (!${Target.ID} && ${Navigation.PathExists[id ${Me.ID}]}) {
				/squelch /e3bcgz /nav id ${Me.ID}
			} else /if (!${Target.ID} && !${Navigation.PathExists[id ${Me.ID}]}) {
				/squelch /e3bcgz /moveto id ${Me.ID} mdist 10
			}
			|-----
			/delay 5
			/target id ${NearestSpawn[npc radius 35 targetable].ID}
			/delay 5
			|------------
			/if (${CurrentTarget}!=${NearestSpawn[npc radius 35 targetable].ID}) {
				/if (${Target.ID}!=0) /message \ayTargetting aggressive mob \aoID: \am[\at${NearestSpawn[npc radius 35 targetable].ID}\am] \aoName: \am[\at${NearestSpawn[npc radius 35 targetable].CleanName}\am]\ay and attacking !\ax
				/ClearTarget usemytarget
				|/keypress esc
				/delay 5
				/varset CurrentTarget ${NearestSpawn[npc radius 35 targetable].ID}
			}
			|------------
		}
		|------------------------------
		
		|------------------------------
		|-- Have a target, kill it.
		|------------------------------
		/if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive}) {				
			|-----
			/if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive} && (${Target.Distance}>20) && ${Navigation.PathExists[id ${Target.ID}]}) {
				/squelch /nav id ${Spawn[npc fleeing].ID}
				/delay 5
				/squelch /e3bcgz /nav id ${Spawn[npc fleeing].ID}
			} else /if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive} && (${Target.Distance}>20) && !${Navigation.PathExists[id ${Target.ID}]}) {
				/squelch /moveto id ${Spawn[npc fleeing].ID} mdist 10
				/delay 5
				/squelch /e3bcgz /moveto id ${Spawn[npc fleeing].ID} mdist 10
			}
			|-----
			/delay 5
			|------------
			/if (${CurrentTarget}!=${Target.ID}) {
				/if (${Target.ID}!=0) /message \ayTargetting aggressive mob \aoID: \am[\at${NearestSpawn[npc radius 35 targetable].ID}\am] \aoName: \am[\at${NearestSpawn[npc radius 35 targetable].CleanName}\am]\ay and attacking !\ax
				/ClearTarget usemytarget
				|/keypress esc
				/delay 5
				/varset CurrentTarget ${Target.ID}
			}
			|------------
		}
		|------------------------------
		
		|------------------------------
		|-- RUNNER: Dont have target, Xtarget MOB may be fleeing.
		|------------------------------
		/if ((${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) || (${Me.XTarget} && ${Spawn[npc fleeing].ID}) || ${Spawn[npc fleeing].ID}) {

			|------------------------------
			/if (${Spawn[npc fleeing].ID}) {	
				|-----
				/if (${Spawn[npc fleeing].ID} && (${Spawn[npc fleeing].Distance}>20) && ${Navigation.PathExists[id ${Spawn[npc fleeing].ID}]}) {
					/squelch /nav id ${Spawn[npc fleeing].ID}
					/delay 5
					/squelch /e3bcgz /nav id ${Spawn[npc fleeing].ID}
				} else /if (${Spawn[npc fleeing].ID} && (${Spawn[npc fleeing].Distance}>20) && !${Navigation.PathExists[id ${Spawn[npc fleeing].ID}]}) {
					/squelch /moveto id ${Spawn[npc fleeing].ID} mdist 10
					/delay 5
					/squelch /e3bcgz /moveto id ${Spawn[npc fleeing].ID} mdist 10
				}
				|-----
				/delay 5			
				/target id ${Spawn[npc fleeing].ID}				
				/delay 5
				|------------
				/if (${CurrentTarget}!=${Spawn[npc fleeing].ID}) {
					/if (${Target.ID}!=0) /message \arFound a \am[\atRandom\am]\ar fleeing mob! \ayTargetting \aoID: \am[\at${Me.XTarget[${i}].ID}\am] \ayName\ao: \am[\at${Me.XTarget[${i}].CleanName}\am]\ay and attacking !\ax
					/ClearTarget usemytarget
					|/keypress esc
					/delay 5
					/varset CurrentTarget ${Spawn[npc fleeing].ID}
				}
				|------------				
			}
			|------------------------------
			
			|------------------------------
			|-- Xtarget
			/if ((${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) || (${Me.XTarget} && ${Spawn[npc fleeing].ID})) {
				|-----
				/if (${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) {
					/message \aoAn XTarget mob is out of range, hunting it down !\ax
				}
				|-----

				|-----
				/if	(${Me.XTarget} && ${Spawn[npc fleeing].ID}) {
					/message \aoXTarget mob is fleeing, chasing it down !\ax
				}
				|-----				
			
				|------------------
				/if	(${Me.XTarget}) {
					/for i 1 to ${Me.XTargetSlots}
						/if (${Me.XTarget[${i}].ID}) {	
							|-----
							/if (${Me.XTarget} && (${Me.XTarget[${i}].Distance}>20) && ${Navigation.PathExists[id ${Me.XTarget[${i}].ID}]}) {
								/squelch /nav id ${Me.XTarget[${i}].ID}
								/delay 5
								/squelch /e3bcgz /nav id ${Me.XTarget[${i}].ID}
							} else /if (${Me.XTarget} && (${Me.XTarget[${i}].Distance}>20) && !${Navigation.PathExists[id ${Me.XTarget[${i}].ID}]}) {
								/squelch /moveto id ${Me.XTarget[${i}].ID}
								/delay 5
								/squelch /e3bcgz /moveto id ${Me.XTarget[${i}].ID}
							}
							|-----
							/delay 5			
							/target id ${Me.XTarget[${i}].ID}
							/delay 5		
							|------------
							/if (${CurrentTarget}!=${Me.XTarget[${i}].ID}) {
								/if (${Target.ID}!=0) /message \arFound a \am[\atXTarget\am]\ar fleeing mob! \ayTargetting \aoID: \am[\at${Me.XTarget[${i}].ID}\am] \ayName\ao: \am[\at${Me.XTarget[${i}].CleanName}\am]\ay and attacking !\ax
								/ClearTarget usemytarget
								|/keypress esc
								/delay 5
								/varset CurrentTarget ${Me.XTarget[${i}].ID}
							}
							|------------
							/break
						}
					/next i
				}				
				|------------------
			}
			|------------------------------
		}
		|------------------------------
		|-- RUNNER
		|------------------------------	
		
		|------------------------------
		| Target Distance Stick Check
		|------------------------------
		/if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive} && (${Target.Distance} > 20)) {	
			/if (${Target.ID}!=0) /message \ayMob \aoID: \am[\at${Target.ID}\am] \ag|\ax \aoName: \am[\at${Target.CleanName}\am]\ay \ag|\ax \aoDistance: \am[\at${Target.Distance}\am]\ay is \ar[TOO FAR AWAY]\ay, adjusting group !\ax
			|--
			/if (${Navigation.PathExists[id ${Target.ID}]}) {
					/squelch /nav id ${Target.ID}
					/delay 2s ${Target.Distance}<=20
					/squelch /e3bcgz /nav id ${Me.ID}					
				} else {
					/squelch /moveto id ${Target.ID} mdist 10
					/delay 2s ${Target.Distance}<=20
					/squelch /e3bcgz /moveto id ${Me.ID} mdist 10
			}
			|--
			/stick 15
			/delay 5
		} else {
			/stick 15
			/delay 5
		}
		|------------------------------

		|------------------------------
		| Target LineOfSight Check
		|------------------------------
		/if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive} && !${Target.LineOfSight}) {	
			/if (${Target.ID}!=0) /message \ayMob \aoID: \am[\at${Target.ID}\am] \ag|\ax \aoName: \am[\at${Target.CleanName}\am]\ay \ag|\ax \aoDistance: \am[\at${Target.Distance}\am]\ay is \ar[NOT IN LINE OF SIGHT]\ay, adjusting group !\ax
			|---------------------
			/if (${Navigation.PathExists[id ${Target.ID}]}) {
					/squelch /nav id ${Target.ID}
					/delay 2s ${Target.LineOfSight}
					/squelch /face fast
					/squelch /e3bcgz /nav id ${Me.ID}					
				} else {
					/squelch /moveto id ${Target.ID} mdist 10
					/delay 2s ${Target.LineOfSight}
					/squelch /face fast
					/squelch /e3bcgz /moveto id ${Me.ID} mdist 10
			}
			|---------------------
		}		
		|------------------------------	
		
		|------------------------------
		/if (${Target.Type.Find[corpse]}) {
			/squelch /target clear
		}
		|------------------------------
			
		|-------------------------- DO BURNS -----------------------------------------
        /if (${Target.ID} && ${Me.Combat} && ${Target.Type.Equal[npc]} && ${DoBurns}) {
			| --- Explosion of Spite
			/if (${SpawnCount[npc radius 50]} >2 && ${Spawn[npc radius 50].Aggressive} && ${Cast.Ready[749]}) {
				/alt act 749
				/if (${DoBurns}) /quickburn
				/if (${DoBurns}) /longburn
				/delay 20
				/goto :gotoloopkeepfighting
			}
			| --- Explosion of Hatred
			/if (${SpawnCount[npc radius 50]} >4 && ${Spawn[npc radius 50].Aggressive} && ${Cast.Ready[822]}) {
				/alt act 822
				/if (${DoBurns}) /fullburn
				/delay 20
				/goto :gotoloopkeepfighting
			}
			| --- Projection of Doom
			/if (${SpawnCount[npc radius 50]} >6 && ${Spawn[npc radius 50].Aggressive} && ${Cast.Ready[3215]} && ${DoBurns}) /alt act 3215
			| --- EpicBurn
			/if (${SpawnCount[npc radius 50]} >4 && ${Spawn[npc radius 50].Aggressive} && ${DoBurns}) /epicburn
			| --- Vicious Bite of Chaos
			/if ((${Me.PctHPs} < 95) && ${Cast.Ready[825]} && ${DoBurns})  /alt act 825
			| --- Chattering Bones
			/if (${Cast.Ready[3822]} && ${DoBurns}) /alt act 3822
			| --- Encroaching Darkness
			/if ((${SpawnCount[npc radius 50]} <3) && ${Spawn[npc radius 50].Aggressive} && ${Cast.Ready[826]}) {
				/squelch /e3bcgz /nav target
				/assistme
				/alt act 826
			}
            /delay 2s
            /if (${Debugging}) /echo DEBUG: KillMob: Combat Loop

            /goto :gotoloopkeepfighting
        }
		|-------------------------- DO BURNS -----------------------------------------
		|--------------------------------------------------
		/if	(${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]} || (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive})) /goto :gotoloopkeepfighting
		|--------------------------------------------------
	}
	|--------------------------------------------------

	|----------------------
	|--- Reset CurrentTarget
	|----------------------
	/varset CurrentTarget 0
	|----------------------
	
	|------------------------
	|-- FORCE TURN OFF PBAE
	|------------------------
	/if (${PBAE_State}) {			
			/varset PBAE_State FALSE
			/message \aoPBAE is currently \am[\arENABLED\am]\ao, disabling \am[\atPBAE\am]\ao now.\ax
			/pbaeoff
	}
	|------------------------
	
	|------------------------
	
	|-----------------------------------
	/if (!${Me.XTarget} || (!${Target.ID} && !${Bool[${Spawn[npc radius 50].Aggressive}]})) /squelch /target clear
	|-----------------------------------
	/if (${Debugging}) /echo Sub DoClearTargets Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckPBAELogic
| --------------------------------------------------------------------------------------------
Sub CheckPBAELogic
	/if (${Debugging}) /echo CheckPBAELogic Sub Entry
	
	|-- TURN ON PBAE
	/if (!${PBAE_State} && ${Target.ID} && (${Target.Distance}<=25) && (${SpawnCount[npc radius 25]}>=${PBAOE_MobCount}) && ${Bool[${Spawn[npc radius 25].Aggressive}]}) {
		/varset PBAE_State TRUE
		/message \aoPBAE is currently \am[\agDISABLED\am]\ao: ~ \am[\arENABLING\am]\ao ~ \am[\atPBAE\am]\ao now.\ax
		/popcustom 13 2 -> PBAE ON <
		/pbaeon
	}
	|-- TURN OFF PBAE
	/if (${PBAE_State} && ${Target.ID} && (${Target.Distance}<=25) && (${SpawnCount[npc radius 25]}<${PBAOE_MobCount}) && ${Bool[${Spawn[npc radius 25].Aggressive}]}) {			
		/varset PBAE_State FALSE
		/message \aoPBAE is currently \am[\arENABLED\am]\ao: ~ \am[\agDISABLING\am]\ao ~ \am[\atPBAE\am]\ao now.\ax
		/popcustom 2 2 -> PBAE OFF <-
		/pbaeoff
	}
	|-------------------------------------------------------------

	/if (${Debugging}) /echo CheckPBAELogic Sub Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoSinglePull_Any
| --------------------------------------------------------------------------------------------
Sub DoSinglePull_Any(string Enemy)
	/if (${Debugging}) /echo DoSinglePull_Any Sub Entry
	|-------------------------
	/call CheckCasting
	|-------------------------
	
	|--------------------------------------------------
	/if (${Bool[${Enemy}]}) {
		/varset FarmMob ${Enemy}
		/if (${Debugging} && !${reportTarget}) {
			/message Looking for: ${FarmMob}
			/varset reportTarget ${reportTarget.OriginalValue}
		}
	} else /if (!${reportTarget}) {
		/message \arAttacking \ay[\apAnything I can get my grubby paws on\ay]\ar.
		/varset reportTarget ${reportTarget.OriginalValue}
		|--------------------------------------------------	
		/if (${myTargetID} && !${Target.Type.Equal[Corpse]} && !${Target.Type.Equal[PC]}) {
			/if (${Spawn[id ${Target.ID}]} && ${Spawn[id ${Target.ID}].Distance} < 30) {
				/if (${Target.ID}) /face
				/squelch /attack on
				|/if (${Select[${Me.Class.ShortName},SHD,MAG,NEC,BST,SHM,ENC,DRU]} && ${Me.Pet.ID}) /pet attack
				/if (${UseClickDamage}) /call Clickies_Damage
				/call DoClearTargets
				/doevents
			}
			/varcalc BackUpTimer (${BackUpTimer})+1
			/if (${BackUpTimer}>7) {
				/message \ayHaving trouble getting to a target.. Attempting to get back on mesh.
				/if (${Debugging}) /echo Setting BackUpTimer Plus 1
				/call BackUp
				/varset BackUpTimer 0
			}
			/if (${AssistMe}) {
				/if (${Debugging}) /e3bcg (Line: ${Macro.CurLine}) killthis
				/squelch /e3bcg /nav id ${Me.ID}
				/squelch /e3bcg /target id ${Me.XTarget}
				/timed 10 /squelch /e3bcgz /assistme
				/call DoClearTargets
				/doevents
				|/timed 15 /squelch /e3bcgz /pet attack
				|/timed 20 /squelch /e3bcgz /pet swarm
			}
			|--------------------------------------------------
		}
		|--------------------------------------------------
	}
	|--------------------------------------------------
	
	:findMob
	/if (${Debugging}) /echo FindMob DoSinglePull
	/if (${Target.Type.Equal[corpse]}) {
		/if (${Target.ID} == ${myTargetID}) /varset myTargetID 0
		/squelch /target clear
	}
	/if (${Window[RespawnWnd].Open}) /call GroupDeathChk
	/if (!${Me.XTarget} && ${CheckBots}) {
		/call GroupDeathChk
		/call GroupManaChk
		/call GroupEndChk
	}
	/if (${Debugging}) /echo \aymyTargetID has an ID: ${Spawn[id ${myTargetID}].ID} - is a corpse: ${Spawn[id ${myTargetID}].Type.Equal[Corpse]} - I have an XTarget: !${Me.XTarget}
	/if (!${Spawn[id ${myTargetID}].ID} || ${Spawn[id ${myTargetID}].Type.Equal[Corpse]} && !${Me.XTarget} && !${Me.Casting.ID}) {
		/message \ayLooking for a target!
		/varset myTargetID 0
		|-------------------
		/call TargetShortest
		|-------------------
		/delay 1s
		/message \atMy Target: \ay[\ap${Spawn[id ${myTargetID}].Name}\ay]
	} else {
		/if (${Debugging}) /echo \ayI have an XTarget so I'm going to set that as my target.
		/if (${Me.XTarget}) {
			/varset myTargetID ${Me.XTarget}
			|---------------------------------------
			/if (${Debugging}) /echo CALL COMBAT
			/if (${Me.XTarget} && ${Spawn[id ${Target.ID}].Distance} < 30) /call combat
			/if (${Debugging}) /echo END CALL COMBAT
			|---------------------------------------
		}
	}
	:navto
	/if (${Debugging}) /echo DoSinglePull NAVTO
	|/if (${Target.ID}) /squelch /target clear
	
	|------------------------------------------------------
	|--- USED IF WE ENABLE PULLING WITH SHT ---
	|------------------------------------------------------
	|--/if (${Spawn[${myTargetID}].Distance} > ${If[${PullAbilityRange},${PullAbilityRange},1]} && !${Target.Type.Equal[corpse]} && !${Me.XTarget} && ${PullRequiresLineOfSight} && !${Spawn[${myTargetID}].LineOfSight}) {
	|------------------------------------------------------
	|--- USED IF WE ENABLE PULLING WITH SHT ---
	|------------------------------------------------------	
	
	|-----------------------
	/if ((${Spawn[${myTargetID}].Distance} > 30) && !${Target.Type.Equal[corpse]} && !${Me.XTarget}) {
		/if (!${Spawn[${myTargetID}].ID}) {
			/squelch /target clear
			/if (${Debugging}) /echo \ar My target ID was null, so I'm returning out of the sub.
			/return
		}
		/varset BackUpTimer 0
		/message \agNavigating to: \ay[\ap${Spawn[${myTargetID}].CleanName}\ay] \agID: \ay[\ap${myTargetID}\ay] \agDistance: \ay[\ap${Spawn[${myTargetID}].Distance}\ay]
		/if (${Debugging}) /echo \ayNavigating to ${Spawn[${myTargetID}].Name} ID: ${myTargetID} Distance: ${Spawn[${myTargetID}].Distance} > ${If[${PullAbilityRange},${PullAbilityRange},30]} - Line of Sight: ${Spawn[${myTargetID}].LineOfSight}
		/call WaitNav ${myTargetID}
		/delay 10
		/if (${Debugging}) /echo Navigating to the enemy.
		/call SetLoc
		/call CheckStuck
		/delay 5
		/goto :navto
	} else /if (${Me.XTarget}) {
		/if (${Navigation.Active}) /nav stop	
		/call DoClearTargets
	} else /if (!${Target.ID} || ((${Target.ID} != ${myTargetID}) && (${Target.ID} != ${Me.ID}) && (${myTargetID} != 0) && !${Me.XTarget})     ) {
		/target id ${myTargetID}
		/if (${Navigation.Active}) /nav stop
	}
	|-----------------------
	/delay 5
	|----------------------------------------------------------------------------------------------------
	/docommand ${If[${PullAbilityRange}>30,/stop,/stick moveback uw 10]}
	/if (${Spawn[${myTargetID}].Distance}<=30 && !${Spawn[${myTargetID}].Aggressive}) /multi ; /squelch /attack on ; /face
	|----------------------------------------------------------------------------------------------------
	|-----------------------------------------------
	/if (${Debugging}) /echo DoSinglePull_Any Sub Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: TargetShortest
| --------------------------------------------------------------------------------------------
Sub TargetShortest
	/if (${Debugging}) /echo Sub TargetShortest Entry
	
	/target clear
	/delay 5

	/if (${UseClickBuffs}) /call Clickies_Buffs
	/declare MobsInRadius 	int 	local 	${SpawnCount[npc noalert 1 targetable radius ${RV_CampRadius} zradius ${RV_ZRadius} alert 10]}


	|- Makes scanning in big zones super efficient.
	/if (${MobsInRadius} > 5) {
		/varset MobsInRadius 5
	}
	/declare MobCounter 	int 	local 	0
	/declare MobID 			int 	local 	0
	/declare PathLength		float	local	0
	/declare MobIDDistance	float	local	0
	/declare PathCount		int		local	1
	/declare PathShortest	int 	local 	0
	/declare MobIDValid		int		local	0
	/if (${Resting}) /return

	/varset myTargetID 0
	/if (${MobsInRadius}) {
		/for MobCounter 1 to ${MobsInRadius}
		/varset MobID ${NearestSpawn[${MobCounter},npc targetable radius ${RV_CampRadius} zradius ${RV_ZRadius} alert 10 noalert 1].ID}

		|-- ORIGINAL LIST TO FILTER
		|/if (${Select[${Spawn[ID ${MobID}].Type},PET,AURA,BANNER,CAMPFIRE,CORPSE,CHEST,ITEM,TRIGGER,TRAP,TIMER,MOUNT,MERCENARY,OBJECT]} && !${Ini[${MobIgnore},${Zone.ShortName},Ignored].Find[ID ${MobID}]}) /continue

		|-- REVISED LIST TO FILTER
		/if (${Select[${Spawn[ID ${MobID}].Type},PC,Untargetable,Mount,Pet,Corpse,Chest,Trigger,Trap,Timer,Item,Mercenary,Aura,Object,Banner,Campfire,Flyer]} && !${Ini[${MobIgnore},${Zone.ShortName},Ignored].Find[ID ${MobID}]}) /continue

		|-- Filter out anything without an actual CleanName ( DOORS )
		/if (!${Spawn[ID ${MobID}].CleanName.Length}) /continue

		|-- Filter out anything with an actual Surname   ( Named )
		/if (${Spawn[ID ${MobID}].Surname.Length}) /continue

		|------- HARD CODED EXCEPTIONS
		|/if (${Spawn[ID ${MobID}].CleanName.Equal[a hatchling]} || ${Spawn[ID ${MobID}].CleanName.Equal[a creaking crate]} || ${Spawn[ID ${MobID}].CleanName.Equal[a hollow tree]} || ${Spawn[ID ${MobID}].CleanName.Equal[a petrified colossal tree]}) {
		|/continue
		|}
		|------- HARD CODED EXCEPTIONS

		/varset MobIDValid 0
		/varset PathLength ${Navigation.PathLength[id ${MobID}]}
		/if (${PathLength} > 0) {
			/if (${PathCount}==1) {
				/varset myTargetID ${MobID}
				/varset PathShortest ${PathLength}
			} else /if (${PathLength} <= ${PathShortest}) {
				/varset myTargetID ${MobID}
				/varset PathShortest ${PathLength}
			}
			/varcalc PathCount ${PathCount}+1
		}

		/next MobCounter
		/if (${myTargetID}) /message \agPulling \ay[\ap${Spawn[${myTargetID}].CleanName}\ay] \agNPCID:\ay[\ap${myTargetID}\ay] \awat \ay[\at${PathShortest}\ay] \awfeet.
		/varset Announce FALSE
		/varset notkillable 0
	} else {
		/varset myTargetID 0
		/delay 5s ${Me.XTarget} == 0
		/if (!${Me.XTarget}) {
			/if (!${Announce}) {				
				/if (!${Me.XTarget}) /call ReturnToCamp
				/message No more mobs to pull, lets Wait for Respawn!
				/varset Announce TRUE
			}
			/varset notkillable 0
			/if (${Me.Standing} && !${Navigation.Active}) /sit
		}
		/if (${Me.XTarget}) /return
	}
	/delay 1
	/if (${Debugging}) /echo Sub TargetShortest exit
	/varcalc BackUpTimer (${BackUpTimer})+1
	/if (${Debugging}) /echo Setting BackUpTimer +1 to ${BackUpTimer}
	/if (${Debugging} && ${BackUpTimer}>1) /echo \arCould Be Stuck ${BackUpTimer}
	|------------------------
	/if (${BackUpTimer}>10) {
		/if (!${Me.XTarget}) /call ReturnToCamp
		/delay 1s
		/message \ayHaving trouble getting to a target.. Attempting to get back on mesh.
		/if (${Debugging}) /echo Setting BackUpTimer Plus 1
		/call BackUp
		/delay 1s
		/varset BackUpTimer 0
	}
	|------------------------
	
	/if (${Debugging}) /echo Sub TargetShortest Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Combat
| --------------------------------------------------------------------------------------------
Sub Combat
	/if (${Debugging}) /echo Sub Combat Entry
	/if (${Target.ID} && (${Target.Type.Equal[npc]} || ${Target.Type.Equal[pet]})) {
		/if (${Navigation.Active}) /squelch /nav stop
		/stick uw loose moveback 8
		|/setchattitle Killing ${Target.CleanName}
		/if (${AssistMe} && !${UseCWTN} && !${UseRGMercs}) {
			/if (${Debugging}) /e3bcg (Line: ${Macro.CurLine}) killthis
			/squelch /e3bcg /nav id ${Me.ID}
			/squelch /e3bcg /target id ${Me.XTarget}
			/timed 10 /squelch /e3bcg /pet attack
			/timed 15 /squelch /e3bcg /pet swarm
			/timed 20 /squelch /e3bcg /assistme
		}
		/if (${Select[${Me.Class.ShortName},SHD,MAG,NEC,BST,SHM,ENC,DRU]} && ${Me.Pet.ID}) {
			/pet attack
			}
		/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
		/if (${Me.XTarget} && ${Spawn[id ${Target.ID}].Distance} < 30) {
				/if (${Target.ID}) /face
				/squelch /attack on
				/doevents
				/if (${UseClickDamage}) /call Clickies_Damage
			}
		:waitTillDead

		/if (${Target.ID} && ${Me.CombatState.Equal[Combat]} && (${Target.Type.Equal[npc]} || ${Target.Type.Equal[pet]})) {
			/if (!${Me.Combat}) {
			/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
			/if (${Select[${Me.Class.ShortName},SHD,MAG,NEC,BST,SHM,ENC,DRU]} && ${Me.Pet.ID}) {
			/pet attack
			}
			/if (${Me.XTarget} && ${Spawn[id ${Target.ID}].Distance} < 30) {
				/if (${Target.ID}) /face
				/squelch /attack on
				/doevents
				/if (${UseClickDamage}) /call Clickies_Damage
			}
			}
			/if (${Me.Class.CanCast} && ${UseCastSpells}) {
				/if (!${Defined[i]}) {
					/declare i int local 0
				}
				/if (!${Me.Casting.ID}) {
					/for i 1 to ${Me.NumGems}
						/if (!${Me.XTarget}) /break
						/if (${Me.Gem[${i}].ID}) {
							/if (${Me.Gem[${i}].TargetType.Equal[Single]} && ${Me.Gem[${i}].SpellType.Equal[Detrimental]} && !${Target.Buff[${Me.Gem[${i}].Name}].ID}) {
								/cast ${i}
								/delay 3s ${Me.Casting.ID}
								/message \agCasting \am${Me.Gem[${i}]} \aw--> \ar${Target.CleanName}
								/delay ${Math.Calc[${Me.Gem[${i}].CastTime.TotalSeconds}+2].Int}s !${Me.Casting.ID}
							}
						}
					/next i
				}
			}

			/delay 10
			/if (${Me.XTarget} && ${Spawn[id ${Target.ID}].Distance} < 30) {
				/if (${Target.ID}) /face
				/squelch /attack on
				/doevents
				/if (${UseClickDamage}) /call Clickies_Damage
			}
			/goto :waitTillDead
			/varset notkillable 0
		} else /if (${Target.Type.Equal[corpse]}) {
			/target clear
			/varset myTargetID 0
		}
	} else /if (${Me.XTarget}) {
		/if (${Spawn[id ${Me.XTarget} radius 30 zradius 50].ID} && ${Spawn[id ${Me.XTarget} radius 30 zradius 50].LineOfSight}) {
			/if (${Navigation.Active}) /nav stop
			/if (${AssistMe}) {
                /if (${Debugging}) /e3bcg (Line: ${Macro.CurLine}) target XTarget ${Spawn[id ${Me.XTarget}].Name}
                /squelch /e3bcg /target id ${Me.XTarget}
            } else {
                /target id ${Me.XTarget}
				/if (${Spawn[id ${Me.XTarget}].Distance} > 30) /squelch /nav id ${Me.XTarget}
				/if (${Select[${Me.Class.ShortName},SHD,MAG,NEC,BST,SHM,ENC,DRU]} && ${Me.Pet.ID}) {
					/pet attack
					}
				/if (${Me.XTarget} && ${Spawn[id ${Target.ID}].Distance} < 30) {
				/if (${Target.ID}) /face
				/squelch /attack on
				/doevents
				/if (${UseClickDamage}) /call Clickies_Damage
			}
            }
			|/setchattitle Handling add, ${Spawn[${Me.XTarget}].CleanName}
		} else /if (${Spawn[id ${Me.XTarget}].Distance} > 30 || !${Spawn[id ${Me.XTarget} radius 30 zradius 50].LineOfSight}) {
			/squelch /nav id ${Me.XTarget}
			/if (!${Me.CombatState.Equal[Combat]}) {
                /if (${Debugging}) /e3bcg (Line: ${Macro.CurLine}) target me and stick (DoSinglePull1).
                /squelch /e3bcg /target id ${Me.ID}
                /delay 5
                /squelch /e3bcg /stick 10 loose moveback uw
            }
			|/setchattitle Navigating to add ${Spawn[id ${Me.XTarget}].CleanName}
			/varset BackUpTimer 0
			/while (${Spawn[${Me.XTarget}].Distance} > 30) {
				/if (!${Navigation.Active}) {
					/squelch /nav id ${Me.XTarget}
					/if (!${Me.CombatState.Equal[Combat]}) {
                        /if (${Debugging}) /e3bcg (Line: ${Macro.CurLine}) target me and stick (DoSinglePull2).
                        /squelch /e3bcg /target id ${Me.ID}
                        /delay 5
                        /squelch /e3bcg /stick 10 loose moveback uw
                    }
                }
                /delay 10
				/if (!${courseCorrection}) {
					/squelch /nav id ${Me.XTarget}
					/varset courseCorrection ${courseCorrection.OriginalValue}
				}
			/call SetLoc
			/call CheckStuck
			/call GMCheck
			}
		}
            /if (${AssistMe} && !${UseCWTN} && !${UseRGMercs}) {
                /if (${Debugging}) /e3bcg (Line: ${Macro.CurLine}) killthis
				/squelch /e3bcg /nav id ${Me.ID}
                /squelch /e3bcg /target id ${Me.XTarget}
                /timed 10 /squelch /e3bcg /pet attack
                /timed 15 /squelch /e3bcg /pet swarm
                /timed 20 /squelch /e3bcg /assistme
            }
		/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
		/if (${Select[${Me.Class.ShortName},SHD,MAG,NEC,BST,SHM,ENC,DRU]} && ${Me.Pet.ID}) {
			/pet attack
			}
		/if (${Me.XTarget} && ${Spawn[id ${Target.ID}].Distance} < 30) {
				/if (${Target.ID}) /face
				/squelch /attack on
				/doevents
				/if (${UseClickDamage}) /call Clickies_Damage
			}
		|/setchattitle Killing ${Target.CleanName}
		/goto :waitTillDead
		/varset notkillable 0
	}
	/if (${Debugging}) /echo Sub Combat Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoSinglePull_Name
| --------------------------------------------------------------------------------------------------
Sub DoSinglePull_Name(string Enemy)
	/if (${Debugging}) /echo DoSinglePull_Name Sub Entry
	|-----------------------------------------------
	
	/message ==================================================================
	|------------------------------------------------
	|--- Remove any comma from the zone name ----
	|------------------------------------------------
	/message \ag - ORIGINAL ZONE NAME\ao=\am(\at${ValidZoneName}\am)\ax
	/if (${ValidZoneName.Find[,]}) {
		|/echo ${ValidZoneName} \arhas\ax a COMMA in it !
		|/echo \arNeed to Modify Zone Name.\ax
		|/echo CutPart 1=(${Zone.Name.Arg[1,,]})
		|/echo CutPart 2=(${Zone.Name.Arg[2,,]})
		/message  \ag - MODIFIED\ay=\am(\at${Zone.Name.Arg[1,,]} ${Zone.Name.Arg[2,,]}\am)\ax
		/varset ValidZoneName ${Zone.Name.Arg[1,,]} ${Zone.Name.Arg[2,,]}
	} else {
		/message \at - ${ValidZoneName}\ax \agdoes NOT have\ax a COMMA in it !\ax
		/message \at - No need to Modify Zone Name.\ax
	}
	/message \agFinal ZONE NAME\ao=\am(\at${ValidZoneName}\am)\ax
	|------------------------------------------------
	|--- Remove any comma from the zone longname ----
	|------------------------------------------------
	/message ==================================================================
	
	|------------------------------------------------------------
	|Mob Array Information.
	|------------------------------------------------------------
	/call ReadINIFile ${ZoneDataFileName} "${ValidZoneName} - (Mob)" Mob
	/if (!${Defined[RV_MobArray]}) {
		/message Mob Array Creation Error, ending macro...
		/endmacro
	}
	|------------------------------------------------------------
	
	:MainLocLoopCycle_Name
	/delay 1s
	/message ==================================================================
	/message \ag+++\ax \ayStarting \ar${HuntMethod} \agCycle:\ax \ao...\ax \arLets go !\ax
	/message ==================================================================
	/delay 3s

	|-------------------------------------------------------------------------------------------------------
	|--------------------
	|--- MAIN CODE HERE FOR NAME PULLS
	|--------------------
	|-------------------------------------------------------------------------------------------------------
	:StartNamePulls
	/doevents
	/call GetTarget
 
	|------------------- Initiat Combat LOGIC -----------------|
	
	|----------------------------------------------
	
	|----------------------------------------------------------
	/if (!${Me.Combat} && !${Me.XTarget}) {
		|----------------------------------------------
		|-- Just nav to loc, using NavToLoc function will cause you to engage mobs along the path !
		|----------------------------------------------
		
		|----------------------------------------------
		/if (${RV_HasTarget}) {		
			|-----
			/if (${Navigation.PathExists[id ${Target.ID}]}) {
				/squelch /nav id ${Target.ID} 
				/delay 7
				/squelch /e3bcgza /nav id ${Target.ID} 
			} else {
				/squelch /moveto id ${Target.ID} mdist 10			
				/delay 7
				/squelch /e3bcgza /moveto id ${Target.ID} mdist 10
			}
			|-----
		}
		|----------------------------------------------
	}
	|------------------------------
	/while (${Navigation.Active}) {
		/call SetLoc
		/call CheckStuck
		/delay 5
	}
	|------------------------------
	/squelch /e3bcgz /nav id ${Me.ID}
	/delay 5
	|----------------------------------------------------------
	
				
	|----------------------------------------------	
	/if (${RV_HasTarget}) /call CombatSub
	|------------------- Add Logic -----------------| 
	/call CheckAggro
	/call CheckForAdds
	|------------------- Add Logic -----------------| 

	|----------------------------------------------------------------
	|-- Clear the camp location of any corpses before the next cycle.
	|----------------------------------------------------------------
	/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
	|----------------------------------------------------------------	
	
	|------------------------------------------
	/if (!${Me.XTarget} && ${CheckBots}) {
		/call GroupDeathChk
		/call GroupManaChk
		/call GroupEndChk
	}
	|------------------------------------------	

	/call ResetSub
	/goto :StartNamePulls
	|-------------------------------------------------------------------------------------------------------
	|--------------------
	|--- MAIN CODE HERE FOR NAME PULLS
	|--------------------
	|-------------------------------------------------------------------------------------------------------
	
	/message ==================================================================
	/message \ag+++\ax \aoCompleted \ar${HuntMethod} \agCycle:\ax \ao...\ax \agLets do it again !!!\ax
	/message ==================================================================
	/delay 3s
	|------------------------

	/goto :MainLocLoopCycle_Name
	
	|-----------------------------------------------
	/if (${Debugging}) /echo DoSinglePull_Name Sub Exit
/return
| --------------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
|SUB: GetTarget
| --------------------------------------------------------------------------------------------------
  Sub GetTarget
  /declare RV_CurrentRadius   int local
  /declare RV_TargetSub   int local
  /declare BadMeTarget int local 0
  /declare BadPCTarget int local 0

:Acquire
  /call CheckAggro
  /if (${Target.Type.Equal[Corpse]}) /squelch /target clear
  
  /for RV_CurrentRadius 10 to ${RV_MaxRadius} step ${RV_StepValue}
    /for RV_TargetSub 1 to ${RV_MobArray.Size}
    :BadTarget
      /if (${Target.ID}==${Me.ID}) {
        /if (!${BadMeTarget}) /message You have yourself on target, pausing macro until /tar clear
        /varset BadMeTarget 1
        /delay 1s
        /goto :BadTarget
      }
      /if (${Target.Type.Equal[PC]}) {
        /if (!${BadPCTarget}) /message You have a PC on target, pausing macro until /tar clear
        /varset BadPCTarget 1
        /delay 1s
        /goto :BadTarget
      }
      /varset BadMeTarget 0
      /varset BadPCTarget 0

    |/echo Mob array size = ${RV_MobArray.Size}
    |/echo RV_TargetSub = ${RV_TargetSub}
    |/echo Mob to target: "${RV_MobArray[${RV_TargetSub}]}"

      /message - Looking for: (\at${RV_MobArray[${RV_TargetSub}]}\ax) distance (\ag${RV_CurrentRadius}\ax).
    |/echo Will use: /squelch /target targetable radius ${RV_CurrentRadius} notid ${RV_InvalidTargetID} npc "${RV_MobArray[${RV_TargetSub}]}"
    
    /squelch /target targetable radius ${RV_CurrentRadius} notid ${RV_InvalidTargetID} npc "${RV_MobArray[${RV_TargetSub}]}"
     |/squelch /target targetable radius ${RV_CurrentRadius} nopcnear notid ${RV_InvalidTargetID} npc "${RV_MobArray[${RV_TargetSub}]}"

      /delay 2 ${Target.ID}

      /varset RV_MyTargetID ${Target.ID}
      /varset RV_MyTargetDead 0
	  
	  |------------------------------
	  |-- Target Validation Rules ---
	  |------------------------------
      /if (${Target.ID}) {
	  
	    | -- MOB CAN BE LOWER THAN 100% (FROM DS) AND STILL VALID, SO WE USE RV_GetMobAtFullHealth TO IGNORE THIS CONDITION LIMITATION
        /if (${RV_GetMobAtFullHealth} && ${Int[${Target.PctHPs}]}<100) {
          /message \ar Mob NOT a Full Health, (${Int[${Target.PctHPs}]}) picking another...\ax
          /varset RV_InvalidTargetID ${Target.ID}
          /call ResetSub
          /goto :Acquire
        }
		
        /if (${Int[${Target.Z}]}<${RV_MinZRange}) {
          /message \ar Mob is BELOW Min Z Range, (${Int[${Target.Z}]}) picking another...\ax
          /varset RV_InvalidTargetID ${Target.ID}
          /call ResetSub
          /goto :Acquire
        }
		
        /if (${Int[${Target.Z}]}>${RV_MaxZRange}) {
          /message \ar Mob is ABOVE Max Z Range, (${Int[${Target.Z}]}) picking another...\ax
          /varset RV_InvalidTargetID ${Target.ID}
          /call ResetSub
          /goto :Acquire
        }
		
        /if (${Target.ID}==${Me.ID}) {
          /message \ar You have yourelf targeted...\ax
          /varset RV_InvalidTargetID ${Target.ID}
          /call ResetSub
          /squelch /target clear
          /goto :Acquire
        }

        /if (${Target.Type.Equal[PC]}) {
          /message \ar You have a PC targeted...\ax
          /varset RV_InvalidTargetID ${Target.ID}
          /call ResetSub
          /squelch /target clear
          /goto :Acquire
        }
		
        /if (${Select[${Target.ID},${Group.Member[0].Pet.ID},${Group.Member[1].Pet.ID},${Group.Member[2].Pet.ID},${Group.Member[3].Pet.ID},${Group.Member[4].Pet.ID},${Group.Member[5].Pet.ID}]}) {
          /message \ar You have a group member's pet targeted...\ax
          /varset RV_InvalidTargetID ${Target.ID}
          /call ResetSub
          /squelch /target clear
          /goto :Acquire
        }		
		
        /varset RV_HasTarget 1
        /varset RV_MyTargetName ${Target.CleanName}
        /message \ar+\ax Acquired (\at${Target.CleanName}\ax) at range (\ag${Int[${Target.Distance}]}\ax).
        /return
      }
      /call CheckAggro
    /next RV_TargetSub
    /delay 2
  /next RV_CurrentRadius

  /if (!${Target.ID}) {
    /delay 1s
    /varcalc RV_FailCounter ${RV_FailCounter}+1
	/message \ar *** Failed \awto Acquire Target in Range\ao: \am(\ag${RV_MaxRadius}\ax\am) \aw--- \am(\ag${RV_FailCounter}\ax\am) \awTime(s\am)
	/delay 1s
    /if (${RV_FailCounter}>=${RV_FailMax}) {
		/call ReturnToCamp
		/varset RV_FailCounter 0
		/return
    }
    /goto :Acquire
  }

  /return
| --------------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
|SUB: CombatSub
| --------------------------------------------------------------------------------------------------
  Sub CombatSub
  /message \ar --- Attacking Mob NOW! \ax
  /varset RV_Fighting 1
  /varset RV_TargetDead 0

  |------------------------------------------------------
  | Call for melee Assist via E3 / EQBCS
  |------------------------------------------------------
  /if (${Select[${Me.Class.ShortName},WAR,SHD,PAL,BER,BST,MNK,RNG,ROG]}) {
	/squelch /attack on
	/if (${Target.ID}) /face
	|----------------------------------------
	/if (${InAGroup}) {
		/timed 5  /squelch /e3bcg /target ID ${Target.ID}
		/timed 10 /squelch /e3bcg /assistme
		/timed 15 /squelch /e3bcg /pet attack
		/timed 20 /squelch /e3bcg /pet swarm
	}
	|----------------------------------------
  }  
  |------------------------------------------------------
  
:CombatLoop
  /doevents
  
  /if (!${Target.ID}) {
    /if (${Target.Type.Equal[Corpse]}) /squelch /target clear
    /attack off
    /keypress forward
    /keypress back

    /varset RV_TargetDead 1
    /varset RV_Fighting 0
    /delay 1s
    /squelch /target radius 50 corpse
    /delay 5 ${Target.ID}
    /if (!${Target.ID}) {
      /call ResetSub
      /return
    }
    /if (${Target.ID}) /face nolook
  }
  /if (!${RV_TargetDead}) {
    /goto :CombatLoop
  }
  /return
| --------------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
|SUB: Check Aggro
| --------------------------------------------------------------------------------------------------
  Sub CheckAggro

  /if (!${Target.ID} && ${Me.XTarget}) {
    /target id ${Me.XTarget}
    /varset RV_MyTargetID ${Target.ID}
    /varset RV_MyTargetDead 0
    /varset RV_HasTarget 1
    /varset RV_MyTargetName ${Target.CleanName}
  }

  /return
| --------------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
|SUB: CheckForAdds
| --------------------------------------------------------------------------------------------------
  Sub CheckForAdds

  |------------------------------------------------------------
  | CHECK FOR ADDS BEFORE LOOTING
  |------------------------------------------------------------
  /if (${Me.XTarget}) {
    /message \ar*** Looks like we have adds ! ***\ax
    /delay 5
    /varset RV_HasTarget 1
    /varset RV_Fighting 1
  }
  |------------------------------------------------------------

  /return
| --------------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
|SUB: Reading from an INI File
| --------------------------------------------------------------------------------------------------
  Sub ReadINIfile(FileName,SectionName,ArrayType)
  
  /message \ayAttempting to Read Section "[\ag${SectionName}\ay]" Zone Information from \at${FileName}\ay...
  /delay 1s

  |------------------------------------------------------
  /if (!${Ini[${FileName},${SectionName}].Length}) {
    /message \ao"[\ar${SectionName}\ao]"\ax \ayis not a Valid Section for\ax \agFILE\ao:\at${FileName}\ay, ending macro...\ax
    /delay 1s
    /return
  }
  |------------------------------------------------------

  /declare nValues     int local  1
  /declare nArray      int local  0
  /declare KeySet      string local  ${Ini[${FileName},${SectionName}]}
  /declare TempMobArrayVal string local null
  /declare TempLocArrayVal string local null

:CounterLoop
  /if (!${KeySet.Arg[${nValues},|].Length}) {
    /varcalc nValues ${nValues}-1
    /goto :MakeArray
  }
  /varcalc nValues ${nValues}+1
  /goto :CounterLoop

:MakeArray
  /if (!${nValues}) /return
  |------------------------------------------------------------------------------------------
  /if (${ArrayType.Equal[Mob]} && ${FileName.Equal["${ZoneDataFileName}"]} && ${nValues}>0) {
    /message \ayDeclaring Mob Array...
    /declare RV_MobArray[${nValues}]   string outer
	/declare RV_MobStats[${nValues}]   string outer
	/message ==================================================================
	/for nArray 1 to ${nValues}
		/if (${FileName.Equal["${ZoneDataFileName}"]}) {
			/varset TempMobArrayVal ${Ini[${FileName},${SectionName},${ArrayType}${nArray}]}
			/if (!${TempMobArrayVal.Equal[NULL]}) /varset RV_MobArray[${nArray}] ${Ini[${FileName},${SectionName},${ArrayType}${nArray}]}
			/if (!${TempMobArrayVal.Equal[NULL]}) /message \atRV_MobArray[${nArray}]\ax \ay${Ini[${FileName},${SectionName},${ArrayType}${nArray}]}\ax
			/varset RV_MobStats[${nArray}] 0
		}	
	/next nArray
	/message ==================================================================		
  }
  |------------------------------------------------------------------------------------------
  
  |------------------------------------------------------------------------------------------
  /if (${ArrayType.Equal[Loc]} && ${FileName.Equal["${ZoneDataFileName}"]} && ${nValues}>0) {
    /message \ayDeclaring Loc Array...
    /declare RV_LocArray[${nValues}]   string outer
	/message ==================================================================
	/for nArray 1 to ${nValues}
		/if (${FileName.Equal["${ZoneDataFileName}"]}) {
			/varset TempLocArrayVal ${Ini[${FileName},${SectionName},${ArrayType}${nArray}]}
			/if (!${TempLocArrayVal.Equal[NULL]}) /varset RV_LocArray[${nArray}] ${Ini[${FileName},${SectionName},${ArrayType}${nArray}]}
			/if (!${TempLocArrayVal.Equal[NULL]}) /message \atRV_LocArray[${nArray}]\ax \ay${Ini[${FileName},${SectionName},${ArrayType}${nArray}]}\ax
		}	
	/next nArray
	/message ==================================================================	
  }
  |------------------------------------------------------------------------------------------
  
  /message "${SectionName}" Zone Information Read Successfully from ${FileName}...
  /delay 5

  /return
| --------------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
| SUB: LocPullStepMove   Receive: SpawnPull_Step from Go2LastSwarmLoc
| --------------------------------------------------------------------------------------------------
Sub LocPullStepMove(string LocPull_Step)
	/declare x 						int 	local 	${LocPull_Step}
	/declare TempSpawnPull_Loc		string 	local	NULL
	/declare mStrLoc				string	local	NULL
	/declare mNavLocY				int		local	NULL
	/declare mNavLocX				int		local	NULL
	/declare SpawnsAtStep			int		local	NULL		
	
	/if (${Debugging}) /echo Sub LocPullStepMove Entry
	/if (${Debugging}) /echo LocPull_Step=(${LocPull_Step})

	:MainLocLoopCycle_Loc
	/delay 1s
	/message ==================================================================
	/message \ag+++\ax \ayStarting \ar${HuntMethod} \agCycle:\ax \ao...\ax \arLets go !\ax
	/message ==================================================================
	/delay 3s
	|-------------------------------------------------------------------------------------------------------
    /for x ${LocPull_Step} to ${RV_LocArray.Size}
		/varset TempSpawnPull_Loc ${RV_LocArray[${x}]}
		|/echo {TempSpawnPull_Loc}=${TempSpawnPull_Loc} | {TempSpawnPull_Loc.Length}=${TempSpawnPull_Loc.Length}
		|-----------------------------
		/if (${TempSpawnPull_Loc.Equal[NULL]}) {
			/message \ar The location steps did not load correctly, reloading !
			/call DoLocPull
			/delay 1s
		}
		|-----------------------------

		|------------------------------------------
		/varset mNavLocY ${TempSpawnPull_Loc.Arg[1, ]}
		/varset mNavLocX ${TempSpawnPull_Loc.Arg[2, ]}
		|-------------------------
		/if (${mNavLocY}>=0) {
            /varset mStrLoc ${mNavLocX} ${mNavLocY}
        } else {
            /varset mStrLoc (${mNavLocX} ${mNavLocY})
        }
		 |-------------------------
		/varset SpawnsAtStep ${SpawnCount[npc loc ${mNavLocX} ${mNavLocY} radius 40]}
		|/echo SpawnsAtStep=(${SpawnsAtStep})
		|/echo  mStrLoc=(${mStrLoc}) | mNavLocY=(${mNavLocY}) | mNavLocYX(${mNavLocX})
		|------------------------------------------

		|------------------------------------------
		/if (!${Me.XTarget} && ${CheckBots}) {
			/call GroupDeathChk
			/call GroupManaChk
			/call GroupEndChk
		}
		|------------------------------------------

		|------------------------------------------
		| Move group to me before next step
		|------------------------------------------
		/message \at - Calling the group to me before moving to the next step . . . .
		/call GroupWait
		/delay 1s
		|------------------------------------------

		|-------------------------
		/call CheckCasting
		|-------------------------

		|-----------------------------------------------
		|/echo \arSwarmPullStepMove: \ayTempSpawnPull_Loc=(${TempSpawnPull_Loc})
		|-----------------------------------------------
		
		/if (${TempSpawnPull_Loc.Length}>0) {
			/message \agNext location to Nav to is: \aySTEP: \ay[\am${x}\ay] of \ay[\am${RV_LocArray.Size}\ay] Coordinates: [\am${TempSpawnPull_Loc}\ay]
			|-----------------------------------------------------------------------------------------------------------------------------
			/if (${SpawnsAtStep}>=1) {
				/message  \ao - STEP: \ay[\am${x}\ay] of \ay[\am${RV_LocArray.Size}\ay] has [\at${SpawnsAtStep}\ay] spawns, \agKILL THEM ALL\ax \ao!!!\ax
				|--------------------------------------------------------------
				|/echo \agARRAY RETURNED DATA for step \ay[${x}]\ag: TempSpawnPull_Loc=(\am${TempSpawnPull_Loc})
				|--------------------------------------------------------------
				/if (!${Me.Combat} && !${Me.XTarget}) {
					|----------------------------------------------
					|-- Just nav to loc, using NavToLoc function will cause you to engage mobs along the path !
					|----------------------------------------------
					/squelch /nav loc ${TempSpawnPull_Loc}
					/delay 7
					/squelch /e3bcgza /nav loc ${TempSpawnPull_Loc}
					|----------------------------------------------
				}
				|------------------------------
				/while (${Navigation.Active}) {
					/call SetLoc
					/call CheckStuck
					/delay 5
				}
				|------------------------------
				/squelch /e3bcgz /nav id ${Me.ID}
				/delay 5
				|----------------------------------------------------------

				|-------------------------------------------------------------------------------------------------------
				|- WRITE: LastLoc_Zone and LastLoc_Step to ini file, to pickup at this point if we break macro.
				|-------------------------------------------------------------------------------------------------------
				/call IniChange "Zone" "LastLoc_Zone" ${Zone.ShortName}
				/call IniChange "Zone" "LastLoc_Step" ${x}
				|-------------------------------------------------------------------------------------------------------
			} else {
				/message  \ao - STEP: \ay[\am${x}\ay] of \ay[\am${RV_LocArray.Size}\ay] has [\at${SpawnsAtStep}\ay] spawns, \arSKIPPING\ax \ao!!!\ax
				|-------------------------------------------------------------------------------------------------------
				|- WRITE: LastLoc_Zone and LastLoc_Step to ini file, to pickup at this point if we break macro.
				|-------------------------------------------------------------------------------------------------------
				/call IniChange "Zone" "LastLoc_Zone" ${Zone.ShortName}
				/call IniChange "Zone" "LastLoc_Step" ${x}
				|-------------------------------------------------------------------------------------------------------
			}
			|-----------------------------------------------------------------------------------------------------------------------------
			|---------------------------------------------------------------
			| Use the DoClearTargets for LocPullStepMove system instead, of COMBAT
			|---------------------------------------------------------------
			/if (${Me.XTarget}) /call DoClearTargets
			/doevents
			/delay 10
		}
		|-----------------------------------------------
		| Before we go to next step ...   ECheck if we should loot Corpses.
		/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
		| Before we go to next step ...   EXIT the loop if we have mission success !
		|-----------------------------------------------
    /next x
	|-------------------------------------------------------------------------------------------------------

	|---------------		
	|-- MOVE TO CAMP
	|---------------
	/call ForceSpawnStepReset
	/call ReturnToCamp
	/delay 5
	
	|----------------------------------------------------------------
	|-- Clear the camp location of any corpses before the next cycle.
	|----------------------------------------------------------------
	/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
	|----------------------------------------------------------------

	|------------------------------------------
	/if (!${Me.XTarget} && ${CheckBots}) {
		/call GroupDeathChk
		/call GroupManaChk
		/call GroupEndChk
	}
	|------------------------------------------

	/message ==================================================================
	/message \ag+++\ax \aoCompleted \ar${HuntMethod} \agCycle:\ax \ao...\ax \agLets do it again !!!\ax
	/message ==================================================================
	/delay 3s
	
	|------------------------
	/call Go2LastSwarmLoc
	|------------------------

	/goto :MainLocLoopCycle_Loc

	|----------------------------------------------------------------------------------------------
	/if (${Debugging}) /echo Sub LocPullStepMove Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: ReturnToCamp     ( Always Call This to pick up From LastLoc_Step )
| --------------------------------------------------------------------------------------------
Sub ReturnToCamp
	/if (${Debugging}) /echo Sub ReturnToCamp Enter
	/message ==================================================================
	/message \ag+++\ax \aoCompleted \ar${HuntMethod} \agCycle:\ax \ao...\ax \atRETURNING TO CAMP !!!\ax
	/message ==================================================================
	|-----------------------
	/if (${Group.Members}>0) {
			/squelch /e3bcgza /nav loc ${CampReturnLoc}
	} else {
			/squelch /nav loc ${CampReturnLoc}
	}
	|-----------------------
	/delay 5
	
	:WaitTillAtCamp
	/if (${Me.Moving}) /delay 5
	/if (${Me.Moving}) /goto :WaitTillAtCamp
	
	|--------------
	/call GroupWait
	|--------------
	
	|------------------
	/if (${ReclaimDC}) /call ReclaimAltDC
	|------------------
	
	/if (${RV_SpawnRecheckTimer}>0) /call WaitForSpawns
	
	/if (${Debugging}) /echo Sub ReturnToCamp Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: WaitForSpawns     ( Always Call This to pick up From LastLoc_Step )
| --------------------------------------------------------------------------------------------
Sub WaitForSpawns
	/if (${Debugging}) /echo Sub WaitForSpawns Enter
	
	/message ==================================================================
	/message \ag+++\ax \aoWaiting \ar${RV_SpawnRecheckTimer}s\ax \aofor re-spawns.\ax
	/message ==================================================================

	|-----------------------------------------------
	/if (!${Me.Combat} && !${Me.XTarget}) {
		/delay ${RV_SpawnRecheckTimer}s
		/call DoClearTargets
	} else {
		/call DoClearTargets		
	}
	|-----------------------------------------------
	
	/if (${Debugging}) /echo Sub WaitForSpawns Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Go2LastSwarmLoc     ( Always Call This to pick up From LastLoc_Step )
| --------------------------------------------------------------------------------------------
Sub Go2LastSwarmLoc
	/if (${Debugging}) /echo Sub Go2LastSwarmLoc Entry
	|------------------------------------------------------------------------------------------------------------
	|- READ:  LastLoc_Zone and LastLoc_Step from ini file, to pickup at this point if restarted macro.
	|------------------------------------------------------------------------------------------------------------
	/varset LastLoc_Zone ${Ini[${IniFileName},Zone,LastLoc_Zone]}
	/varset LastLoc_Step ${Ini[${IniFileName},Zone,LastLoc_Step]}
	|-------------------------------------------------------------------------------------------------------
	|/echo \arGo2LastSwarmLoc: \ayLastLoc_Zone=(${LastLoc_Zone}) | LastLoc_Step=(${LastLoc_Step})
	|-------------------------------------------------------------------------------------------------------
	/if (${Debugging}) /echo LastLoc_Zone=(${LastLoc_Zone}) | LastLoc_Step=(${LastLoc_Step})
	/message \agThe last known spawn pull \aySTEP\ag is: \ay[\am${LastLoc_Step}\ay]

	|--------------------------------------------------------------------------------------------------------------------------
	| - Call the SwarmPullStepMove function and pass the location and step from INI file
	| - (The Array Values have already defined from DoSwarmPull)
	| -
	| If we are in same dungeon, pickup from LastSwarmed_Loc .. else..  run the path fresh !
	| SwarmPullStepMove will pick up the path in a loop where the step number will change X in the loop !
	|--------------------------------------------------------------------------------------------------------------------------
	|/echo {Zone.ShortName}=(${Zone.ShortName}) | {Ini.File.Zone.Name}=(${LastLoc_Zone})
	|-----------------------------------------------------------------------
	| Change values to pass STEP 1 if we arent in the last recorded dungeon.
	|-----------------------------------------------------------------------
	/if (!${Zone.ShortName.Equal[${LastLoc_Zone}]}) {
		/call ForceSpawnStepReset
	}
	|-----------------------------------------------------------------------
	|/echo \arGo2LastSwarmLoc: \ay/call SwarmPullStepMove_1 ${LastLoc_Step}
	|-----------------------------------------------------------------------

	|-----------------------------------
	|- Retrieve the last mission results
	|-----------------------------------
	/call LocPullStepMove ${LastLoc_Step}
	|-----------------------------------------------------------------------

	|--------------------------------------------------------------------------------------------------------------------------
	/if (${Debugging}) /echo Sub Go2LastSwarmLoc Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
| SUB: ForceSpawnStepReset
| --------------------------------------------------------------------------------------------------
Sub ForceSpawnStepReset
/if (${Debugging}) /echo Sub ForceSpawnStepReset Entry

	/message \arForcing LastLoc_Step reset to step \ay(\at1\ay)

	|----------------------------------------------------------
	| -- Write STEP 1 to the ini file since we want to set our initial first step for that zone.
	|------------------------------------------
	/call IniChange "Zone" "LastLoc_Step" 1
	/varset LastLoc_Step 1
	/delay 20
	|------------------------------------------

/if (${Debugging}) /echo Sub ForceSpawnStepReset Exit
/return
| --------------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoLocPull		Note: Define The Array Variables and kick off Go2LastSwarmLoc
| --------------------------------------------------------------------------------------------
Sub DoLocPull
/if (${Debugging}) /echo Sub DoLocPull Entry

	/message ==================================================================
	/message \agSetting up pathing to \ay[\arLocation Pull\ay] \agmobs. . . . .
	|------------------------------------------------
	|--- Remove any comma from the zone name ----
	|------------------------------------------------
	/message \ag - ORIGINAL ZONE NAME\ao=\am(\at${ValidZoneName}\am)\ax
	/if (${ValidZoneName.Find[,]}) {
		|/echo ${ValidZoneName} \arhas\ax a COMMA in it !
		|/echo \arNeed to Modify Zone Name.\ax
		|/echo CutPart 1=(${Zone.Name.Arg[1,,]})
		|/echo CutPart 2=(${Zone.Name.Arg[2,,]})
		/message  \ag - MODIFIED\ay=\am(\at${Zone.Name.Arg[1,,]} ${Zone.Name.Arg[2,,]}\am)\ax
		/varset ValidZoneName ${Zone.Name.Arg[1,,]} ${Zone.Name.Arg[2,,]}
	} else {
		/message \at - ${ValidZoneName}\ax \agdoes NOT have\ax a COMMA in it !\ax
		/message \at - No need to Modify Zone Name.\ax
	}
	/message \agFinal ZONE NAME\ao=\am(\at${ValidZoneName}\am)\ax
	|------------------------------------------------
	|--- Remove any comma from the zone longname ----
	|------------------------------------------------
	/message ==================================================================
		
	|------------------------------------------------------------
	|Mob Array Information.
	|------------------------------------------------------------
	/call ReadINIFile ${ZoneDataFileName} "${ValidZoneName} - (Loc)" Loc
	/if (!${Defined[RV_LocArray]}) {
		/message Loc Array Creation Error, ending macro...
		/endmacro
	}
	|------------------------------------------------------------

	|----------------------------------------------------
	/message \agGet ready, the fun is starting soon !
	/delay 5
	/if (${Me.XTarget}) /call DoClearTargets
	/delay 10
	|- Call Go2LastSwarmLoc after Defining Array
	/call Go2LastSwarmLoc
	|----------------------------------------------------
	
/if (${Debugging}) /echo Sub DoLocPull Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: NavToLoc -- [NO Combat and Agro Aware movement]
| --------------------------------------------------------------------------------------------
Sub NavToLoc(int Y,int X,int Z)
	/if (${Debugging}) /echo Entering Sub NavToLoc for ${Y} ${X} ${Z} at Line: ${Macro.CurLine}
	/varset GroupWaitTimer 0
	/message \at-- NavToLoc \ay[\amNo Combat & Agro aware movement\ay] \atto \ay[\am${Y} ${X} ${Z}\ay]\at.
	|-------------------------------------------------------------------------------
	/while (${Math.Distance[${Me.Y}, ${Me.X}, ${Me.Z}: ${Y}, ${X}, ${Z}]} > 30) {
		/if (${Navigation.Active}) {
			/if (${CheckBots}) /call GroupDeathChk
			/if (${CheckBots}) /call GroupManaChk
			/if (${CheckBots}) /call GroupEndChk
			/call GMCheck
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL DoSinglePull NavToLoc
				/call DoSinglePull_Any
			} else {
				/if (${CheckBots}) /call GroupDeathChk
				/if (${CheckBots}) /call GroupManaChk
				/if (${CheckBots}) /call GroupEndChk
				/call GMCheck
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/delay 10
		} else {
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL FARM STUFF NavToLoc II
				/call DoSinglePull_Any
			} else {
				/if (${CheckBots}) /call GroupDeathChk
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/if (!${Me.Combat} && !${Me.XTarget}) /call Group2Me
			/if (!${Me.Moving}) /squelch /e3bcgza /nav loc ${Y} ${X} ${Z}
			/delay 5 ${Me.Moving}
			/delay 5 ${Navigation.Active}
		}
	}
	|-------------------------------------------------------------------------------
	/delay 2s
	/if (${Navigation.Active}) /nav stop
	/if (${Debugging}) /echo Sub NavToLoc Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: NavToLoc2 -- [Combat and Agro Aware movement]
| --------------------------------------------------------------------------------------------
Sub NavToLoc2(int Y,int X,int Z)
	/if (${Debugging}) /echo Entering Sub NavToLoc2 for ${Y} ${X} ${Z} at Line: ${Macro.CurLine}
	/varset GroupWaitTimer 0
	/message \at-- NavToLoc2 \ay[\amCombat & Agro aware movement\ay] \atto \ay[\am${Y} ${X} ${Z}\ay]\at.
	/while (${Math.Distance[${Me.Y}, ${Me.X}, ${Me.Z}: ${Y}, ${X}, ${Z}]} > 20) {
		/if (${Navigation.Active}) {
			/if (${Debugging}) /echo WaitNav Moving ELSE
			/if (${CheckBots}) /call GroupDeathChk
			/if (${CheckBots}) /call GroupManaChk
			/if (${CheckBots}) /call GroupEndChk
			/call GMCheck
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/popcustom 13 5 ---> GOT AGGRO ON ROUTE <---
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL DoSinglePull NavToLoc	
				/target id ${NearestSpawn[npc radius 35 targetable].ID}
				/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
				/if (${Spawn[id ${Target.ID}].Distance} < 30) {
					|------  CALL GROUP TO ME To FIGHT
					/call Group2Me
					|------  CALL GROUP TO ME To FIGHT									
					/if (${Target.ID}) /face
					/squelch /attack on
					/call DoClearTargets
					/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
					/doevents
					/if (${UseClickDamage}) /call Clickies_Damage
				}
			} else {
				/if (${Debugging}) /echo WaitNav Moving ELSE
				/if (${CheckBots}) /call GroupDeathChk
				/if (${CheckBots}) /call GroupManaChk
				/if (${CheckBots}) /call GroupEndChk
				/call GMCheck
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/delay 10
		} else {
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/popcustom 13 5 ---> GOT AGGRO ON ROUTE <---
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL FARM STUFF NavToLoc II
				/target id ${NearestSpawn[npc radius 35 targetable].ID}
				/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
				/if (${Spawn[id ${Target.ID}].Distance} < 30) {
					|------  CALL GROUP TO ME To FIGHT
					/call Group2Me
					|------  CALL GROUP TO ME To FIGHT				
					/if (${Target.ID}) /face
					/squelch /attack on
					/call DoClearTargets
					/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
					/doevents
					/if (${UseClickDamage}) /call Clickies_Damage
				}
			} else {
				/if (${CheckBots}) /call GroupDeathChk
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/if (!${Me.Moving} && !${Me.Combat} && !${Me.XTarget}) /squelch /e3bcgza /nav loc ${Y} ${X} ${Z}
			/delay 5 ${Me.Moving}
			/delay 5 ${Navigation.Active}
		}
	}
	/delay 2s
	/if (${Navigation.Active}) /nav stop
	/if (${Debugging}) /echo Sub NavToLoc2 Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: WaitNav
| --------------------------------------------------------------------------------------------
Sub WaitNav(NavTargetID)
	/if (${Debugging}) /echo \agEntering Sub WaitNav for ${Spawn[id ${NavTargetID}].Y} ${Spawn[id ${NavTargetID}].X} ${Spawn[id ${NavTargetID}].Z} at Line: ${Macro.CurLine}
	/message \at-- WaitNav \ay[\amNo Combat & Agro aware movement\ay] \atto mob id:\ay[\am${NavTargetID}\ay]\at.
	/if (!${Spawn[id ${NavTargetID}].ID}) {
		/delay 5s
		/return
	}
	/while (${Spawn[id ${NavTargetID}].Distance} > 30 || !${Spawn[${myTargetID}].LineOfSight}) {
		/if (!${Spawn[id ${NavTargetID}].ID}) {
			/delay 5s
			/return
		}
		/if (${Spawn[id ${NavTargetID}].Distance} < 30) {
			/nav stop
		}
		/if (${Spawn[id ${NavTargetID}].ID}) {
			/call SetLoc
			/call CheckStuck
			/call GMCheck
			/if (${Me.XTarget}) {
				/if (${Navigation.Active}) /nav stop
				/varset NavTargetID ${Me.XTarget}
				/if (${Debugging}) /echo CALL FARM STUFF WaitNAV
				/call TargetShortest
			} else {
				/if (${Debugging}) /echo \ayWaitNav Moving
				/if (${CheckBots}) /call GroupDeathChk
				/if (${CheckBots}) /call GroupManaChk
				/if (${CheckBots}) /call GroupEndChk
				/call GMCheck
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/if (!${courseCorrection}) {
				|------  ALL GO TO TARGET - staggered
				/nav id ${NavTargetID}
				/delay 5
				/squelch /e3bcgz /nav id ${NavTargetID}
				|------  ALL GO TO TARGET - staggered
				/varset courseCorrection ${courseCorrection.OriginalValue}
			}
			|----------------------------------
			| Should group come to me on pulls. 
			|----------------------------------
			/if (${GroupNavToMe}) {
                /call Group2Me
            }
			|----------------------------------
			/delay 10
		} else {
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/if (${Navigation.Active}) /nav stop
				/e3bcgza /target id ${Me.XTarget}
				/varset NavTargetID ${Me.XTarget}
				/if (${Debugging}) /echo CALL TargetShortest WaitNav II
				/call TargetShortest
			} else {
				/varcalc BackUpTimer (${BackUpTimer})+1
				/if (${BackUpTimer}>7) {
					/message \ayHaving trouble getting to a target.. Attempting to get back on mesh.
					/if (${Debugging}) /echo Setting BackUpTimer Plus 1
					/call BackUp
					/varset BackUpTimer 0
					/varset NavTargetID 0
					/if (${Me.XTarget}) {
						/varset NavTargetID ${Me.XTarget}
					}
				}
				/if (${Debugging}) /echo WaitNav Moving ELSE
				/if (${CheckBots}) /call GroupDeathChk
				/if (${CheckBots}) /call GroupManaChk
				/if (${CheckBots}) /call GroupEndChk
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/squelch /nav id ${NavTargetID}
		}
	}
	/if (${Navigation.Active}) /nav stop
	:target
	/target id ${NavTargetID}
	/delay 2s ${Target.CleanName.Equal[${Spawn[id ${NavTargetID}].CleanName}]}
	/if (!${Target.CleanName.Equal[${Spawn[id ${NavTargetID}].CleanName}]} && ${Spawn[id ${NavTargetID}].ID} && !${Me.XTarget}) {
		/goto :target
	}
	/if (${Debugging}) /echo Sub WaitNav Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Zoning
| --------------------------------------------------------------------------------------------
Sub Zoning
	/if (${Debugging}) /echo Sub Zoning Entry
	:Zoning
	/delay 2m ${Zone.ID}!=${startZone}
	/target id ${Me.ID}
	/delay 1s ${Target.ID}==${Me.ID}
	/if (!${Navigation.MeshLoaded}) {
		/message \ayWaiting for you to load a mesh for this zone.
		/nav reload
		/delay 5s
		/goto :Zoning
	}
	/delay 2s
	/varset startZone ${Zone.ID}
	/squelch /target clear
	/call CheckMesh
	/delay 2s
	|---------------------------------------------
	| Cleartargets if I have agro on zoning.
	|---------------------------------------------
	/if (${Me.XTarget}) /Call DoClearTargets
	/call Refresh
	/if (${Debugging}) /echo Sub Zoning Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: CheckForCorpses
| --------------------------------------------------------------------------------------------
  Sub CheckForCorpses
  /if (${Debugging}) /echo Sub CheckForCorpses Entry

  /call GMCheck
  /message \ay- Checking for missed corpse(s).
  /if (${Bool[${Spawn[Corpse radius 100]}]}) /message \at+++ \ayLooks like we have a corpse to loot.
  /if (${Target.ID} && (!${Me.XTarget} || !${Bool[${Spawn[npc radius 35].Aggressive}]})) /squelch /target clear
  
:CheckAgain
  |------------------
  /if (${MouseLock}) /mouseto ${MouseLocValX}, ${MouseLocValY}
  |------------------
  |/hidecorpse looted
  /hidecorpse none
  |------------------

  /squelch /target radius 100 corpse
  /delay 5 ${Target.ID}
	
	|----------------------------------------------
	/if (${Target.ID} && ${Target.Type.Equal[Corpse]}) {
		/face fast nolook

		|----------------------------------------------
		|-----
		/if (${Navigation.PathExists[id ${Target.ID}]}) {
			/if (${Target.ID} && ${Target.Type.Equal[Corpse]} && (${Target.Distance}>10) && !${Me.Casting.ID}) /nav id ${Target.ID}
		} else {
			/if (${Target.ID} && ${Target.Type.Equal[Corpse]} && (${Target.Distance}>10) && !${Me.Casting.ID}) /moveto id ${Target.ID} mdist 10
		}
		|-----
		|----------------------------------------------

		|-------------------------
		/call CheckCasting
		/delay 5 !${Me.Moving}	
		|--------------------------------------------------------------------------------
		/if (!${Me.XTarget} && !${Me.Casting.ID} && !${Me.Moving} && ${LootMethod.Equal[TURBOLOOT]}) /call LootMob_Turboloot
		/if (!${Me.XTarget} && !${Me.Casting.ID} && !${Me.Moving} && ${LootMethod.Equal[DCONLY]}) /call LootMob_DC_Only
		/if (!${Me.XTarget} && !${Me.Casting.ID} && !${Me.Moving} && ${LootMethod.Equal[E3]}) /call LootMob_E3
		/delay 5
		|--------------------------------------------------------------------------------
	}
    /squelch /target clear
	|-------------------------
	
    /if (${Bool[${Spawn[Corpse radius 100]}]}) /goto :CheckAgain
  } else {
    /message \ar+++ \ayNo corpse(s) found to loot.\ax
  }

	/if (${Debugging}) /echo Sub CheckForCorpses Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: LootMob_Turboloot -- Let Turboloot Looting handle your corpseloot.
| --------------------------------------------------------------------------------------------
  Sub LootMob_Turboloot
	/if (${Debugging}) /echo Sub LootMob_Turboloot Entry		

	|---------------------------------------
	| -- Let TURBOLOOT Looting System handle this !
	|---------------------------------------
	/if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}) {
		/message \at+++ \ayHaving \am[\ag${TurboLooter}\am]\ay loot via \am[\aoTurboLoot\am]\ay.		
		/message \at+ \aoHiding corpse(s) from myself.
		/hidecorpse all
		/squelch /e3bct ${TurboLooter} /mac TurboLoot
		/message \at+ \aoWaiting on \am[\ag${TurboLooter}\am]\ay to finish looting.
		/varset TurboLootPause TRUE
		/delay 5
		|---------------------------
		/while (${TurboLootPause}) {			
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets			
			/doevents
			/delay 1s
		}
		|---------------------------
		/message \at+++ \ayDone having \am[\ag${TurboLooter}\am]\ay loot via \am[\aoTurboLoot\am]\ay.
	} else {
		/call DoClearTargets
	}
	|---------------------------------------
	| -- Let TURBOLOOT Looting System handle this !
	|---------------------------------------
	|--------------------------------------------
	/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets
	|--------------------------------------------
	/doevents
	|-------------------------------------------------------------------------------------

	/if (${Debugging}) /echo Sub LootMob_Turboloot Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: LootMob_E3 -- Let E3 Looting handle your corpseloot.
| --------------------------------------------------------------------------------------------
  Sub LootMob_E3
	/if (${Debugging}) /echo Sub LootMob_E3 Entry

	/if (${Target.ID} && ${Target.Type.Equal[Corpse]}) /face fast nolook
	/keypress forward
	/keypress back
	/fastdrop on
	/lootn never
	
	|---------------------------------------
	| -- Let E3 Looting System handle this !
	|---------------------------------------
	|---------------------------------------
	| -- HANDLE CONDITIONALY !
	|---------------------------------------
	/if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}) {
		/message \at+++ \ayLooting - \ag Corpse\ao: \ar[\am${Target.CleanName}\ar] \agID\ao: \ar[\am${Target.ID}\ar].
		/loot
	} else {
		/call DoClearTargets
	}
	|---------------------------------------
	| -- HANDLE CONDITIONALY !
	|---------------------------------------
	|---------------------------------------
	| -- Let E3 Looting System handle this !
	|---------------------------------------
	|--------------------------------------------
	/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets
	|--------------------------------------------
	/doevents
	|-------------------------------------------------------------------------------------
	/if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}  && !${Me.Casting.ID} && !${Me.Moving}) /call CheckIfBagsFull
	|-------------------------------------------------------------------------------------

	/if (${Debugging}) /echo Sub LootMob_E3 Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: LootMob_DC_Only: Standard coin and Diamond Coin
| --------------------------------------------------------------------------------------------
  Sub LootMob_DC_Only
    /if (${Debugging}) /echo Sub LootMob_DC_Only Entry
	
	/declare x  		 			int 	inner	1
	/declare LootSlot    			int 	inner	0
    /declare LootCheck  			int 	inner	0
    /declare LootTotal   			int 	inner	0
	/declare CursorItemValueInPlat	int 	inner	0
	/declare NoDropMobID			int		inner	0
	
	/if (${Target.ID} && ${Target.Type.Equal[Corpse]}) /face fast nolook
    /keypress forward
    /keypress back
    /fastdrop on
    /lootn never

	|---------------------------------------
	| -- HANDLE CONDITIONALY !
	|---------------------------------------
	/if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}) {
		/message \at+++ \ayLooting - \ag Corpse\ao: \ar[\am${Target.CleanName}\ar] \agID\ao: \ar[\am${Target.ID}\ar].
		/loot
	} else {
		/call DoClearTargets
	}
	|---------------------------------------
	| -- HANDLE CONDITIONALY !
	|---------------------------------------

	|-------------------------------------
    /delay 1s ${Window[LootWnd].Open}
    /doevents
	|-------------------------------------

	|--------------------------------------
    /if (${Corpse.Items}) {
		/varset LootTotal ${Corpse.Items}
		/message \ay++ Corpse has (\at${LootTotal}\ay) item(s) on it to loot.
		|---------------------------------------
		/for LootSlot 1 to ${LootTotal}
			
			|--------------------------------------------------------
			|---- HANDLE NODROP GANK HUNTED ITEM
			|---- RETURN BACK CORPSE ITEM DATA HERE.
			|--------------------------------------------------------			
			
			|/echo CORPSE ITEM(${LootSlot}):(${Corpse.Item[${LootSlot}].Name})
			
			/if ( ${Select[${Corpse.Item[${LootSlot}].Name},${NoDropGankItems}]} ) {
				|------------------------------------------------------------------------------------------------------------
				|- READ:  LastGankLoot_Member from ini file, Determine if we GANK
				|------------------------------------------------------------------------------------------------------------
				/varset LastGankLoot_Member ${Ini[${IniFileName},Zone,LastGankLoot_Member]}
				/varset NoDropMobItem ${Corpse.Item[${LootSlot}].Name}
				/varset NoDropMobID ${Target.ID}
	
				/if (${LastGankLoot_Member}<6) {
					/message \at+\ax \agKeeping a\ax \ay(\at${Corpse.Item[${LootSlot}].Name}\ay) \ag because it's a \arNO DROP\ax that I need to \amGANK\ax !\ax
					/varset DoGroupGankNoDrop TRUE									
				} else {
					/message \at+\ax \ay(\at${Corpse.Item[${LootSlot}].Name}\ay)\ag dropped, but everyone has one, \amSKIPPING\ax.
					/varset DoGroupGankNoDrop FALSE
				}
				|------------------------------------------------------------------------------------------------------------
				
			} else {
			|--- BEGIN - LOOT AND HANDLE CURSOR ITEM
				/message \ay-- Grabbing corpse item (\am${LootSlot}\ax) of (\am${LootTotal}\ax).				
				/nomodkey /shift /itemnotify Loot${LootSlot} leftmouseup
				/delay 5 ${Cursor.ID}
				/if (${Window[QuantityWnd].Open}) /notify QuantityWnd QTYW_Accept_Button leftmouseup
				/delay 5
	
				|----------------------------------------------------------------------------------------------
				/varset CursorItemValueInPlat ${Math.Calc[${FindItem[=${Cursor.Name}].Value}/1000]}
				|----------------------------------------------------------------------------------------------
				
				|/echo (${Cursor.Name}) -- CursorItemValueInPlat=(${CursorItemValueInPlat}) | {MinItemValue})=${MinItemValue})
				
				|--------------------------------------------------------
				|---- ALL VALUABLE STACKABLE LOOT THAT DROPS IN THIS ZONE
				|--------------------------------------------------------	
				/if (${Cursor.ID}) {			
					/if (${Cursor.Name.Equal[Diamond Coin]}) {
						/message \at+\ax \agKeeping a\ax \ay(\atDiamond Coin\ay) \ag worth \ay(\at${CursorItemValueInPlat}\ay)\ag platinum ... WOOT!\ax
						/autoinventory 
						/delay 5 !${Cursor.ID}
					} else /if (${CursorItemValueInPlat}>=${MinItemValue}) {
						/message \at+\ax \agKeeping a\ax \ay(\at${Cursor.Name}\ay) \ag worth \ay(\at${CursorItemValueInPlat}\ay)\ag platinum ... WOOT!\ax
						/autoinventory 
						/delay 5 !${Cursor.ID}
					}
				}
				|--------------------------------------------------------
	
				|--------------------------------------------------------
				|---- DESTROY ANYTHING REMAINING
				|--------------------------------------------------------
				/if (${Cursor.ID}) {
					/message \ar-\ax \arDestroying a\ax \ay(\at${Cursor.Name}\ay)\ar, that crap is woth less than \ay(\at${MinItemValue}\ay)\ar plat!\ag Sell Val\ao:\at(\ay${CursorItemValueInPlat}\at)\ay.
					/destroy
					/delay 5 !${Cursor.ID}
				}
				|--------------------------------------------------------			
			|--- END - LOOT AND HANDLE CURSOR ITEM
			}
			|--------------------------------------------------------
		/doevents
		|--------------------------------------------
		/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets
		|--------------------------------------------
		/next LootSlot
		|---------------------------------------
    }
    |--------------------------------------

    /notify LootWnd DoneButton leftmouseup
    /delay 1s !${Window[LootWnd].Open}
    |--------------------------------------------
    /if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets
    |--------------------------------------------
    /doevents
  |-----------------------------------------------------------------
  |-- After corpse has been checked, do GroupGankNoDrop if required.
  |-----------------------------------------------------------------
  /if (${DoGroupGankNoDrop}) /call GroupGankNoDrop ${NoDropMobID} "${NoDropMobItem}"
  |-----------------------------------------------------------------
  
  |-------------------------------------------------------------------------------------
  /if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}  && !${Me.Casting.ID} && !${Me.Moving}) /call CheckIfBagsFull
  |-------------------------------------------------------------------------------------
	
  /if (${Debugging}) /echo Sub LootMob_DC_Only Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupGankNoDrop
| --------------------------------------------------------------------------------------------
  Sub GroupGankNoDrop(int GankMob_ID, string GankMob_Item)
  /if (${Debugging}) /echo Sub GroupGankNoDrop Entry
   
	|/echo GankMob_ID=(${GankMob_ID}) | GankMob_Item=(${GankMob_Item})
  
	/declare NextGankLoot_Member int inner 0
  
	|------------------------------------------------------------------------------------------------------------
	|- READ:  LastGankLoot_Member from ini file.
	|------------------------------------------------------------------------------------------------------------
	/varset LastGankLoot_Member ${Ini[${IniFileName},Zone,LastGankLoot_Member]}
	|/echo LastGankLoot_Member=(${LastGankLoot_Member})

	/if (${LastGankLoot_Member}==0) {
		|------------------------------------------------------------------------------------------------------------
		|-- DO MY LOOT PASS SHIT HERE	
		|------------------------------------------------------------------------------------------------------------			
		/message \at+\ax \agI am set to collect a\ax \ay(\at${GankMob_Item}\ay)\ag.
		
		/hidecorpse none
		/delay 1s
		/target ID ${GankMob_ID}
		/delay 2s ${Target.ID}
		/face nolook
		/delay 5
		/moveto id ${Target.ID} mdist 10
		/delay 5
		/fastdrop on
		/delay 5
		/lootn never
		/delay 5
		/multi ; /timed 5 /loot ; /timed 5 /lootall
		/delay 5s
		|------------------------------------------------------------------------------------------------------------
		|-- DO MY LOOT PASS SHIT HERE	
		|------------------------------------------------------------------------------------------------------------			
	} else {
		/message \at+\ax \agNext person set to collect a\ax \ay(\at${GankMob_Item}\ay)\ag is \ay(\at${Group.Member[${LastGankLoot_Member}].CleanName}\ay)\ax.
		|------------------------------------------------------------------------------------------------------------
		|-- DO OTHER MEMBER LOOT PASS SHIT HERE	
		|------------------------------------------------------------------------------------------------------------
		/message \agTelling \ay(\at${Group.Member[${LastGankLoot_Member}].CleanName}\ay)\ag to loot \ay(\at${GankMob_Item}\ay)\ag off of \ay(\atMOBID:${GankMob_ID}\ay)\ag.
	
		/squelch /e3bct ${Group.Member[${LastGankLoot_Member}].CleanName} /multi ; /afollow off ; /nav stop ; /stand
		/delay 1s
		/squelch /e3bct ${Group.Member[${LastGankLoot_Member}].CleanName} /target ID ${GankMob_ID}
		/delay 2s
		/squelch /e3bct ${Group.Member[${LastGankLoot_Member}].CleanName} /face nolook
		/delay 5
		/squelch /e3bct ${Group.Member[${LastGankLoot_Member}].CleanName} /moveto id ${Target.ID} mdist 10
		/delay 3s
		/squelch /e3bct ${Group.Member[${LastGankLoot_Member}].CleanName} /fastdrop on
		/delay 5
		/squelch /e3bct ${Group.Member[${LastGankLoot_Member}].CleanName} /lootn never
		/delay 5
		/squelch /e3bct ${Group.Member[${LastGankLoot_Member}].CleanName} /multi ; /timed 5 /loot ; /timed 5 /lootall
		/delay 5s
		/squelch /e3bct ${Group.Member[${LastGankLoot_Member}].CleanName} /afollow spawn ${Me.ID}
		/delay 5		
		|------------------------------------------------------------------------------------------------------------
		|-- DO OTHER MEMBER LOOT PASS SHIT HERE	
		|------------------------------------------------------------------------------------------------------------		
	}
	
	|-----------------------------------------------------------------------------------------------------------------------
	| -- GET NEXT LastGankLoot_Member 
	|-----------------------------------------------------------------------------------------------------------------------
	/if (${LastGankLoot_Member}<5) {
		/varcalc NextGankLoot_Member (${LastGankLoot_Member})+1
	} else {
		/varset NextGankLoot_Member 999
	}
	|-----------------------------------------------------------------------------------------------------------------------
	| -- Write NEXT LastGankLoot_Member to the ini file, no need to VARSET it since it needs to be read from file each time.
	|-----------------------------------------------------------------------------------------------------------------------
	/call IniChange "Zone" "LastGankLoot_Member" ${NextGankLoot_Member}
	/delay 20
	|------------------------------------------------------------------------------------------------------------
	|- SET DoGroupGankNoDrop to FALSE
	|------------------------------------------------------------------------------------------------------------
	/varset DoGroupGankNoDrop FALSE
	|------------------------------------------------------------------------------------------------------------
	
  /if (${Debugging}) /echo Sub GroupGankNoDrop Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: ResetSub
| --------------------------------------------------------------------------------------------
  Sub ResetSub
  /keypress esc
  /keypress esc
  /keypress esc
  /keypress esc

  /varset RV_HasTarget 0
  /varset RV_TargetDead 0
  /varset RV_Fighting 0

  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: OpenPacks
| --------------------------------------------------------------------------------------------
	Sub OpenPacks
	/declare bag int local 0
	/if (!${Window[InventoryWindow].Open}) /nomodkey /keypress inventory
	/delay 3s ${Window[InventoryWindow].Open}
	/for bag 1 to 10
		/if (!${Window[Pack${bag}].Open}) /nomodkey /itemnotify pack${bag} rightmouseup
		/delay 3s ${Window[Pack${bag}].Open}
		/if (${Window[TradeskillWnd].Open}) /nomodkey /notify TradeskillWnd ExperimentButton leftmouseup
		/delay 5s !${Window[TradeskillWnd].Open}
	/next bag
	/return
|--------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: ClosePacks
| --------------------------------------------------------------------------------------------
	Sub ClosePacks
	/declare bag int local 0
	/if (!${Window[InventoryWindow].Open}) /nomodkey /keypress inventory
	/delay 3s ${Window[InventoryWindow].Open}
	/for bag 1 to 10
		/if (${Window[Pack${bag}].Open}) /nomodkey /itemnotify pack${bag} rightmouseup
		/delay 3s !${Window[Pack${bag}].Open}
	/next bag
	/if (${Window[InventoryWindow].Open}) /nomodkey /keypress inventory
	/delay 3s !${Window[InventoryWindow].Open}
  /return
|--------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoorClick
| --------------------------------------------------------------------------------------------
Sub DoorClick
/if (${Debugging}) /echo Sub DoorClick Entry
	/doortarget
	/delay 1s
	/click left door
/if (${Debugging}) /echo Sub DoorClick Exit
/return
| --------------------------------------------------------------------------------------------

|--------------------------------------------------------
|Group2Me
|--------------------------------------------------------
Sub Group2Me
/if (${Debugging}) /echo Sub Group2Me Entry
	/e3bcgz /nav id ${Me.ID}
/if (${Debugging}) /echo Sub Group2Me Exit
/return
|--------------------------------------------------------

|--------------------------------------------------------
| INIChange
|--------------------------------------------------------
Sub INIChange(Section,Key,Value)
/if (${Debugging}) /echo Sub INIChange Entry
	/ini "${IniFileName}" "${Section}" "${Key}" "${Value}"
/if (${Debugging}) /echo Sub INIChange Exit
/return
|--------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckStuck
| --------------------------------------------------------------------------------------------
Sub CheckStuck
	/if (${Debugging}) /echo Sub CheckStuck Entry
	/if (${Me.Stunned} || !${Navigation.Active}) /return
	/if (${StuckSpamTrigger}) /return
	|/echo ${Math.Distance[${OutY1},${OutX1}]}
	/if (${Math.Distance[${OutY1},${OutX1}]} < 20) {
		/varcalc StuckCountOut (${StuckCountOut})+1
		/if (${StuckCountOut}>6) /message \arStuck ${StuckCountOut}
		/if (${Me.ActiveDisc.Name.Equal[Frenzied Resolve Discipline]}) /stopdisc
		/if (${StuckCountOut}>6) {
				|/call doorclick
				/if (${UseBeep}) {
					/beep
					/delay 1
					/beep
				}
				|/call doorclick
		}
		/varset StuckSpamTrigger 1
	} else {
		/varset StuckCountOut 0
	}
	/if (${StuckCountOut}>=8) {
				/message \ayThink I'm stuck... \agAttempting to get unstuck...
				/call Stuck
				/varset StuckCountOut 0
		}
	/if (${Debugging}) /echo Sub CheckStuck Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Stuck
| --------------------------------------------------------------------------------------------
sub Stuck
/if (${Debugging}) /echo Sub Stuck Entry
/if (${StuckSwitch}) {
	/if (${Debugging}) /echo Hide Corpse STUCK
	/hidecorpse all
	/call BackUp
	/varset myTargetID 0
	/varset StuckSwitch 0
	/varset StuckCountOut 0
	} else {
		|/call DoorClick
		/varset StuckSwitch 1
		/varset StuckCountOut 0
		/varset courseCorrection 0
		/if (${Debugging}) /echo Hide Corpse STUCK
		/hidecorpse none
		}
/if (${Debugging}) /echo Sub Stuck Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: BackUp
| --------------------------------------------------------------------------------------------
Sub BackUp
	/if (${Debugging}) /echo Sub Backup Entry
    /declare strafedir string local
	/target clear
	|/call DoorClick
	/if (${Navigation.Active}) /nav pause
	/if (${Me.FeetWet}) {
		/keypress down hold
		/delay 10
		/keypress PAGE_UP hold
		/delay 20
		/keypress up hold
		/keypress right hold
		/delay 10
		/keypress left
		/keypress down
		/keypress PAGE_DOWN
	}
	/keypress back hold
	/delay 20
	/varset myTargetID 0
	/keypress back
	/if (${Math.Rand[2]}) {
		/varset strafedir STRAFE_LEFT
	} else {
		/varset strafedir STRAFE_RIGHT
	}
	/keypress ${strafedir} hold
	/delay 20
	/keypress ${strafedir}
	/delay 10
	/keypress forward hold
	/delay 10
	/keypress forward
	|/if (!${Navigation.Active}) /nav pause
	/if (${Debugging}) /echo Sub Backup Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: SetLoc
| --------------------------------------------------------------------------------------------
sub SetLoc
	/if (${Debugging}) /echo Sub SetLoc Entry
	/if (${StuckSpamTimerSet} || !${Navigation.Active}) /return
	/varset OutX1 ${Me.X}
    /varset OutY1 ${Me.Y}
	/varset StuckSpamTimerSet 5s
	|----------------------------------------------------------------
	|/echo (${Int[${Me.X}]}==${OutX1}) && (${Int[${Me.Y}]}==${OutY1})
	|----------------------------------------------------------------
	/if (${Debugging}) /echo Sub SetLoc Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupWait
| --------------------------------------------------------------------------------------------
Sub GroupWait
/if (${Debugging}) /echo Sub GroupWait Entry
:WaitForGroup
/if (${Me.XTarget}) {
	/if (${Navigation.Active}) /nav stop
	/call Group2Me
	/call DoClearTargets
	/goto :WaitForGroup
}
/message \ayWaiting for the group. . .

/if (${Debugging}) /echo ${Group.Member[1].CleanName}:(${Group.Member[1].Distance}) ${Group.Member[2].CleanName}:(${Group.Member[2].Distance}) ${Group.Member[3].CleanName}:(${Group.Member[3].Distance}) ${Group.Member[4].CleanName}:(${Group.Member[4].Distance}) ${Group.Member[5].CleanName}:(${Group.Member[5].Distance})

    /while ((${Group.Member[1].Distance} > 40) || (${Group.Member[2].Distance} > 40) || (${Group.Member[3].Distance} > 40) || (${Group.Member[4].Distance} > 40) || (${Group.Member[5].Distance} > 40) || (${Group.Member[6].Distance} > 40)) {
        /message \aywaiting for the group, timer ${GroupWaitTimer}.\ax
		/e3bcgz /stand
		/e3bcgz /nav id ${Me.ID}
        /delay 5s
		/varcalc GroupWaitTimer (${GroupWaitTimer})+1
		/call GroupWaitTimer
		/goto :WaitForGroup
	}
	/varset GroupWaitTimer 0
	/message \ay. . . my group is now here.\ax
	/if (${Debugging}) /echo Sub GroupWait Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupWaitTimer
| --------------------------------------------------------------------------------------------
Sub GroupWaitTimer
	/if (${Debugging}) /echo Sub GroupWaitTimer Entry
	/if (${GroupWaitTimer}==8) /varset GroupWaitTimer 0
	/if (${GroupWaitTimer}==5) {
		/message \ayA Group Member might be stuck!
		/squelch /e3bcgza /stand
		/squelch /e3bcgza /removelev
		/squelch /e3bcgza /moveto loc ${Me.Y} ${Me.X} ${Me.Z}
		/squelch /e3bcgza /keypress back hold
		/delay 3s
		/squelch /e3bcgza /keypress back
	}
	/if (${GroupWaitTimer}==6) {
		/message \ayA Group Member is stuck!
		/squelch /e3bcgza /moveto loc ${Me.Y} ${Me.X} ${Me.Z}
		/squelch /e3bcgza /keypress forward hold
		/delay 2s
		/squelch /e3bcgza /keypress forward
		/delay 2s
	}
	|--- Use Wayfarers Brotherhood Emblem' to COTH the group.
	/if (${GroupWaitTimer}==7 && ${FindItemCount[Wayfarers Brotherhood Emblem]}>0) {
		/message \ayA Group Member is stuck, Attempting to CoH !!!
		/delay 1s
		/coth group
		/delay 1s
		/call CheckCasting
		/delay 5
	}
	/if (${Debugging}) /echo Sub GroupWaitTimer Exit
/return GroupWaitTimer
|--------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckCasting
| --------------------------------------------------------------------------------------------
Sub CheckCasting
	/if (${Debugging}) /echo Sub CheckCasting Entry

	|-------------------------
	:CheckCastingNow
	/if (${Me.Casting.ID}) {
		/message \ag-- Waiting to stop casting.
		/delay 1s !${Me.Casting.ID}
		/goto :CheckCastingNow
		/message \ag-- I am done casting.
		/delay 1s
		/if (${Target.ID} && (!${Me.XTarget} || !${Bool[${Spawn[npc radius 35].Aggressive}]})) /squelch /target clear
	}
	|------------------------

	/if (${Debugging}) /echo Sub CheckCasting Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GMCheck
| --------------------------------------------------------------------------------------------
Sub GMCheck
/if (${Debugging}) /echo Sub GMCheck Entry
/if (${Spawn[gm].ID} && ${AFKGM}) {
				/message \ar WARNING GM nearby!
				/if (${UseBeep}) /beep
				|------------------------------------------------
				/call GMMode
				|------------------------------------------------
				}
/if (${Debugging}) /echo Sub GMCheck Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GMMode
| --------------------------------------------------------------------------------------------
Sub GMMode
/if (${Debugging}) /echo Sub GMMode Entry
		/if (${UseBeep}) /beep
		/popcustom 13 5 Warning! GMMode: GM is Present!
		/message ==================================================================
		/message \ar***** GM IN ZONE, PAUUSING MACRO *****\ax
		/message ==================================================================
		/mqp

/if (${Debugging}) /echo Sub GMMode Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupDeathChk
| --------------------------------------------------------------------------------------------
Sub GroupDeathChk
	/if (${Debugging}) /echo Sub GroupDeathChk Entry
	|--- If ImDead
	/if (${Me.State.Equal[DEAD]}) {
		/message \arYOU~ have died! Waiting for YOU to get off your face.
		|----------
		/while (${Me.State.Equal[DEAD]}) {
			/call GMCheck
			/beep
			/beep
			/beep
			/delay 30
		}
		|----------
	}
	|--- If ImDead
	/if (${Me.XTarget}) /return
	|--- If Group --
	/if (${Group}) {
		/declare i int local
		|----------------------------------
		/for i 1 to ${Group}
			| -- If GroupMember IsDead
			/if (${Group.Member[${i}].State.Equal[DEAD]} ) {
				/message ${Group.Member[${i}].Name} has died. Waiting for them to get off their face.
				|------   If No Target ID
				/if (!${Me.XTarget}) {
					|----------------------------------
					/while (${Group.Member[${i}].State.Equal[DEAD]} && !${Me.XTarget}) {
						/call GMCheck
						/if ((${Me.Standing}) && (!${Me.Casting.ID}) && (!${Me.Mount.ID})) /sit
						/beep
						/delay 30
					}
					/squelch /e3bcg /stand
				}
				|------   If No Target ID
			}
			| -- If GroupMember IsDead
		/next i
		|----------------------------------
	}
	|--- If Group --

	/if (${Debugging}) /echo Sub GroupDeathChk Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupManaChk
| --------------------------------------------------------------------------------------------
Sub GroupManaChk
	/if (${Debugging}) /echo Sub GroupManaChk Entry
	/if (${Me.XTarget}) /return

	|------------------- If NoCombat
	/if (!${Me.Combat}) {
		|---
		|--- If Me LowMana
		/if ((${Me.PctMana} < ${MedAt} && !${Me.State.Equal[DEAD]} && !${Select[${Me.Class.ShortName},WAR,BER,ROG,MNK,BRD]}) || (${BardMed} && ${Me.PctMana} < ${MedAt} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.Equal[BRD]})) {
			/message \arYOU are low on mana!
			/call Group2Me
			|------   If No Target ID
			/if (!${Me.XTarget}) {
				|--------------------------------------
				/while ((${Me.PctMana} < ${MedTill} && !${Me.XTarget} && !${Me.State.Equal[DEAD]} && !${Select[${Me.Class.ShortName},WAR,BER,ROG,MNK,BRD]}) || (${BardMed} && ${Me.PctMana} < ${MedTill} && !${Me.XTarget} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.Equal[BRD]})) {
					/message \agYour \am[\atMana\am]\ag is currently at \am[\at${Me.PctMana}\am]\ag%, medding to \am[\at${MedTill}\am]\ag%.
					/call GMCheck
					/if (${Me.Standing} && !${Me.Casting.ID} && !${Me.Mount.ID} && !${Navigation.Active}) /sit
					/delay 6s
				}
                /squelch /e3bcg /stand
			}
			|------   If No Target ID
		}
		|--- If Me LowMana
		|--- If Group --
		/if (${Group}) {
			/declare i int local
			|--------------------------------------
			/for i 1 to ${Group}
				|------   If Valid GroupMemeber
				/if ((${Group.Member[${i}].PctMana} < ${MedAt} && ${Group.Member[${i}].Class.CanCast} && !${Group.Member[${i}].State.Equal[DEAD]} && !${Select[${Group.Member[${i}].Class.ShortName},BRD,WAR,MNK,BER,ROG]}) || (${BardMed} && (${Group.Member[${i}].PctMana} < ${MedAt}) && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]})) {
					/message \ar${Group.Member[${i}].Name} is low on mana!
					/call Group2Me
					|--------------
					| Make Them Sit
					|--------------
					/squelch /e3bct ${Group.Member[${i}].CleanName} /sit
					|----
					/call Refresh
					|------   If No Target ID
					/if (!${Me.XTarget}) {
						|--------------------------------------
						/while ((${Group.Member[${i}].PctMana} < ${MedTill} && ${Group.Member[${i}].Class.CanCast} && !${Me.XTarget} && !${Group.Member[${i}].State.Equal[DEAD]} && !${Select[${Group.Member[${i}].Class.ShortName},BRD,WAR,MNK,BER,ROG]}) || (${BardMed} && ${Group.Member[${i}].PctMana} < ${MedTill} && !${Me.XTarget} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]})) {
							/message \ag${Group.Member[${i}].CleanName}'s \am[\atMana\am]\ag is currently at \am[\at${Group.Member[${i}].PctMana}\am]\ag%, medding to \am[\at${MedTill}\am]\ag%.
							/call GMCheck
							/if (${Me.Standing} && !${Me.Casting.ID} && !${Me.Mount.ID} && !${Navigation.Active}) /sit
							/delay 3s
							|----------
							/if (${Group.Member[${i}].Standing}) {
								/delay 6s
								/squelch /e3bct ${Group.Member[${i}].CleanName} /sit
							}
							|----------
						}
						/squelch /e3bcg /stand
					}
					|------   If No Target ID
				}
				|------   If Valid GroupMemeber
			/next i
			|--------------------------------------
		}
		|--- If Group --
	}
	|------------------- If NoCombat

	/if (${Debugging}) /echo Sub GroupManaChk Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupEndChk
| --------------------------------------------------------------------------------------------
Sub GroupEndChk
	/if (${Debugging}) /echo Sub GroupEndChk Entry
	/if (${Me.XTarget}) /return

	|------------------- If NoCombat
	/if (!${Me.Combat}) {
		|---
		|--- If Me LowEnd
		/if ((${Me.PctEndurance} < ${MedEndAt} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.NotEqual[BRD]}) || (${BardMed} && ${Me.PctEndurance} < ${MedEndAt} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.Equal[BRD]})) {
			/message \arYOU are low on Endurance!
			/call Group2Me
			|------   If No Target ID
			/if (!${Me.XTarget}) {
				|--------------------------------------
				/while ((${Me.PctEndurance} < ${MedEndTill} && !${Me.XTarget} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.NotEqual[BRD]}) || (${BardMed} && ${Me.PctEndurance} < ${MedEndAt} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.Equal[BRD]})) {
					/message \agYour \am[\atEndurance\am]\ag is currently at \am[\at${Me.PctEndurance}\am]\ag%, medding to \am[\at${MedEndTill}\am]\ag%.
					/call GMCheck
					/if (${Me.Standing} && !${Me.Casting.ID} && !${Me.Mount.ID} && !${Navigation.Active}) /sit
					/delay 6s
				}
                /squelch /e3bcg /stand
			}
			|------   If No Target ID
		}
		|--- If Me LowEnd
		|--- If Group --
		/if (${Group}) {
			/declare i int local
			|--------------------------------------
			/for i 1 to ${Group}
				|------   If Valid GroupMemeber
				/if (${Group.Member[${i}].ID}) {
					|------   If GroupMember LowEnd
					/if ((${Group.Member[${i}].PctEndurance} < ${MedEndAt} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.NotEqual[BRD]}) || (${BardMed} && ${Group.Member[${i}].PctEndurance} < ${MedEndAt} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]})) {
						/message \ar${Group.Member[${i}].Name} is low on Endurance!
						/call Group2Me
						|--------------
						| Make Them Sit
						|--------------
						/squelch /e3bct ${Group.Member[${i}].CleanName} /sit
						/call Refresh
						|------   If No Target ID
						/if (!${Me.XTarget}) {
							|---------------------------------------
							/while ((${Group.Member[${i}].PctEndurance} < ${MedEndTill} && !${Me.XTarget} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.NotEqual[BRD]}) || (${BardMed} && ${Group.Member[${i}].PctEndurance} < ${MedEndTill} && !${Me.XTarget} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]})) {
								/message \ag${Group.Member[${i}].CleanName}'s \am[\atEndurance\am]\ag is currently at \am[\at${Group.Member[${i}].PctEndurance}\am]\ag%, medding to \am[\at${MedEndTill}\am]\ag%.
								/call GMCheck
								/if (${Me.Standing} && !${Me.Casting.ID} && !${Me.Mount.ID} && !${Navigation.Active}) /sit
								/delay 3s
								|----------
								/if (${Group.Member[${i}].Standing}) {
									/delay 6s
									/squelch /e3bct ${Group.Member[${i}].CleanName} /sit
								}
								|----------
						}
						|---------------------------------------
						/squelch /e3bcg /stand
						}
						|------   If No Target ID
					}
					|------   If GroupMember LowEnd
				}
				|------   If Valid GroupMemeber
			/next i
			|--------------------------------------
		}
		|--- If Group --
	}
	|------------------- If NoCombat

	/if (${Debugging}) /echo Sub GroupEndChk Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Refresh
| --------------------------------------------------------------------------------------------
Sub Refresh
/if (${Debugging}) /echo Sub Refresh Entry
/if (${Debugging}) /echo Calling Refresh
	/keypress F2
	/delay 2s
	/keypress F3
	/delay 2s
	/keypress F4
	/delay 2s
	/keypress F5
	/delay 2s
	/keypress F6
	/delay 2s
	/squelch /target clear
	/if (${Debugging}) /echo Sub Refresh Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GetExpeditionData
| --------------------------------------------------------------------------------------------
Sub GetExpeditionData
	/if (${Debugging}) /echo Sub GetExpeditionData Entry
		|--------------------------------------------
		:OpenDynamicZoneWindow
		|--- open the Expedition Window to pull data
		/keypress alt+z
		/delay 1s
		/delay 3s ${Window[DynamicZoneWnd].Open}
		/if (!${Window[DynamicZoneWnd].Open}) /goto :OpenDynamicZoneWindow
		|--------------------------------------------------------------
		|-- Determine if I have a Dranik Catacombs Expedition Assigned.
		|--------------------------------------------------------------
		/varset CurrentExpedition ${Window[DynamicZoneWnd].Child[DZ_CurrentDZValue].Text}
		|--------------------------
		/if (!${CurrentExpedition.Length}==0 && ${CurrentExpedition.Find[Catacombs of Dranik]}) {
			/varset DranikCExpedition 1
		} else {
			/varset DranikCExpedition 0
		}
		|--------------------------
		/keypress alt+z
		|--------------------------------------------
	/if (${Debugging}) /echo Sub GetExpeditionData Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckInADungeon
| --------------------------------------------------------------------------------------------
Sub CheckInADungeon
	/if (${Debugging}) /echo Sub CheckInADungeon Entry
	/if (${Select[${Zone.ID},330]}) {
		/varset InADungeon 1
	} else {
		/varset InADungeon 0
	}
	/if (${Debugging}) /echo Sub CheckInADungeon Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckHaveDranikCExpedition
| --------------------------------------------------------------------------------------------
Sub CheckHaveDranikCExpedition
	/if (${Debugging}) /echo Sub CheckHaveDranikCExpedition Entry

	|--------------------------------------------------------------
	|-- Determine if I have a Dranik Catacombs Expedition Assigned.
	|--------------------------------------------------------------
	/varset CurrentExpedition ${Window[DynamicZoneWnd].Child[DZ_CurrentDZValue].Text}
	|--------------------------
	/if (!${CurrentExpedition.Length}==0 && ${CurrentExpedition.Find[Catacombs of Dranik]}) {
		/varset DranikCExpedition 1
	} else {
		/varset DranikCExpedition 0
	}
	|--------------------------

	/if (${Debugging}) /echo Sub CheckHaveDranikCExpedition Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckINI
| --------------------------------------------------------------------------------------------
Sub CheckINI(string IniName,string Section,string Key,string TypeVar,Default)
    /if (${Debugging}) /echo (IniName:${IniName} Section:${Section} Key:${Key} TypeVar:${TypeVar})
	/if (${Debugging}) /echo Sub CheckINI Entry
	/if (!${Ini[${IniName},${Section},${Key}].Length}) {
		/ini ${IniName} ${Section} ${Key} ${Default}
	}
	/declare ${Key} ${TypeVar} outer ${Ini[${IniName},${Section},${Key}]}
	/message \atLoading \ayINI \ay[\am${IniName}\ay] \ar~ \aoKey: \ag${Key} \aoType: \ag${TypeVar} \aoINI Value: \at\ay[\am${Ini[${IniName},${Section},${Key}]}\ay]
	/if (${Debugging}) /echo Sub CheckINI Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckThings
| --------------------------------------------------------------------------------------------
Sub CheckThings
	/if (${Debugging}) /echo Sub CheckThings Entry
	
	
	/message \ayChecking running status of \am[\atxfix.lua\am]\ao:\ax

	|--------
	/if (!${Lua.Script[xfix].Status.Equal[Running]}) {
		/message \atTrying to start xfix.lua...\ax
		/lua run xfix
		/delay 2s
	}
	|--------

	|--------
	/if (!${Lua.Script[xfix].Status.Equal[Running]}) {
		/message \arxfix.lua can not be started, and it IS needed, exiting !\ax
		/message ==================================================================
		/end
	} else {
		/message \agxfix is already active.
		/message ==================================================================
	}
	|--------	
	
	|-----------------------
	|-- SEET GROUP ROLES ---
	|-----------------------
	/message \aySetting group role(s)\ao:\ax.
	/message \ayMaking myself \am[\atMain Tank\am]\ay.
	/grouproles set ${Me.CleanName} 1
	/delay 5
	/message \ayMaking myself \am[\atMain Assist\am]\ay.
	/grouproles set ${Me.CleanName} 2
	/delay 5
	/message ==================================================================
	/delay 2s
	|-----------------------
	
	|---------------------------------
	| Plugin check - Enabble / disable
	|---------------------------------
	|---------
	/if (${Bool[${Plugin[MQ2Bucles]}]}) {
        /squelch /plugin MQ2Bucles unload noauto
        /message MQ2Bucles detected! This macro doesn't like it! Unloading temporarily ...
    }
	|---------
	/call CheckPlugin MQ2Nav
	/call CheckMesh
	/call CheckPlugin MQ2Events	
	/call CheckPlugin MQ2MoveUtils
	|---------------------------------

	|-------------------------
	|-- CHECK DRIVER PET STATUS
	|-------------------------
	/call CheckDriverPetStatus
	|-------------------------	

	|-------------------------		
	/if (${LootCorpse}) {		
		/message ==================================================================
		/message \ay--- \atENABLING\ax \am${MacroName}\ax LOOTING, WE WILL LOOT CORPSE(S).
		/message ==================================================================		
		/if (${LootMethod.Equal[DCONLY]}) {
			/squelch /lootoff
			/message \ay--- \agLOOTING METHOD:\ax (\am${LootMethod}\ax) we will only loot\ax
			/message \ay    [\atDiamond Coin\ay] and \arHIGH VALUE ITEMS \am(\ao>=\at${MinItemValue}\am)\ay.\ax
			|------------------------------------------------
		}  
		/if (${LootMethod.Equal[E3]}) {
			/squelch /looton
			/message \ay--- \agLOOTING METHOD:\ax (\am${LootMethod}\ax) we will only loot according to \am${LootMethod}\ax settings.
			/message \ay    [ If configured in your \am${LootMethod}\ax config files. \ag("Loot Settings.ini")\ax ]
		}
		/if (${LootMethod.Equal[TURBOLOOT]}) {
			/squelch /lootoff
			/message \ay--- \agLOOTING METHOD:\ax (\am${LootMethod}\ax) we will only loot according to \am${LootMethod}\ax settings.
			/message \ay    [ If configured in your \am${LootMethod}\ax config files. \ag(turboloot.ini)\ax ]
			|-------------
			/if (${TurboLooter.Equal[NOBODY]} || ${TurboLooter.Equal[NULL]} || ${TurboLooter.Equal[${Me.CleanName}]}) {
				/message ==================================================================
				/message \ar    WARNING\ao: \arYOU CAN NOT HAVE TURBOLOOTER SET AS \ar[\at${TurboLooter}\am]\ar.
				/message \ar    It can not be NOBODY or YOURSELF ! \ag ~ FIX AND RESTART ~.\ax
				/message ==================================================================
				/end
			}			
			|-------------
			/message \ay    [ Looter cuurently set to: \am[\at${TurboLooter}\am]\ay   ]			
		}		
		/message ==================================================================
		/delay 3s
	} else {
		/squelch /lootoff
		/message ==================================================================
		/message \ar--- DISABLING \am${MacroName}\ar LOOTING, YOU WILL NOT LOOT CORPSE(S)!
		/message ==================================================================
		/delay 3s
	}
	|-------------------------	

	|-------------------------
	|-- CHECK CLASSES SET VARS
	|-------------------------
	/call CheckGroupClasses
	|-------------------------
		
	|-------------------------
	| Delay to read output.
	|-------------------------
	/delay 3s
	|-------------------------	

	/if (${Endmac}) /end
	/if (${Debugging}) /echo Sub CheckThings Exit

/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckGroupClasses
| --------------------------------------------------------------------------------------------
Sub CheckGroupClasses
	/if (${Debugging}) /echo Sub CheckGroupClasses Entry

	/declare i 					int 	local	0
	/declare targetClasses string local BRD,BER,BST,CLR,DRU,ENC,MAG,MNK,NEC,PAL,RNG,ROG,SHD,SHM,WAR,WIZ

	|--/message ==================================================================
	/message \ayChecking current Group Members \am(\atMe \ao+ \am[\at${Group.Members}\am])\ay against all classes.\ax
	|-- /message \ayClasses to be checked\ao:\ax
	|-- /message \am[\at${targetClasses}\am]\ax

	|---------------------------------------------------
	|---- CREATE DEFAULT CLASS VARIABLES FOR ALL CLASSES
	|---------------------------------------------------
    /for i 0 to ${Group.Members}
		
		|--/message ==================================================================
        |-- /message \ayChecking \am[\at${Group.Member[${i}].CleanName}\am]\ao: \am[\ay${Group.Member[${i}].Class.ShortName}\am] \awItemSelect- \am[\ay${Select[${Group.Member[${i}].Class.ShortName},${targetClasses}]}\am] 
		|------------
		/if (${Select[${Group.Member[${i}].Class.ShortName},${targetClasses}]}) {
            |-- /message Found a target class: \am[\ay${Group.Member[${i}].Class.ShortName}\am] - \am[\ay${Group.Member[${i}].CleanName}\am] \awin \am[\aytargetClasses\am]\ax.
			/if (!${Defined[GrpHas${Group.Member[${i}].Class.ShortName}Class]}) {
				|-- /message \ar--- \agMaking a \am[\atGrpHas${Group.Member[${i}].Class.ShortName}Class\am]\ag DECLARE for class \am[\at${Group.Member[${i}].Class.ShortName}\am]\ax
				/declare GrpHas${Group.Member[${i}].Class.ShortName}Class	bool	outer	TRUE			
				|-- /message \ar--- Created\ao:\aw /declare GrpHas${Group.Member[${i}].Class.ShortName}Class	bool	outer	TRUE
			}
			/message \ay+ \agThe group has a \am[\ao${Group.Member[${i}].Class.ShortName}\am] - \am[\at${Group.Member[${i}].CleanName}\am]\ag.
		}
		|------------
	/next i
    }
	/message ==================================================================
	|---------------------------------------------------
	|---- CREATE DEFAULT CLASS VARIABLES FOR ALL CLASSES
	|---------------------------------------------------	
	
	/if (${Debugging}) /echo Sub CheckGroupClasses Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckDriverPetStatus
| --------------------------------------------------------------------------------------------
Sub CheckDriverPetStatus
	/if (${Debugging}) /echo Sub CheckDriverPetStatus Entry

	|-----------------------------
	/if (${Select[${Me.Class.ShortName},PAL,SHD,WAR]} && ${Me.Pet.ID}) {
		/message ==================================================================
		/message \ay- I have a pet active.\ax
		|----------------------------------
		/if (${Select[${Me.Class.ShortName},PAL,WAR]}) {
			/message \ay- I can not suspend my pet, dismissing it.		
			/pet leave
			/delay 5
		}
		|----------------------------------
		/if (${Me.Class.ShortName.Equal[SHD]}) {
			/message \ay- Attempting to Suspended Minion.	
			|------------------------------
			/if (${Me.AltAbilityReady[Suspended Minion]}) {
				/squelch /alt act 176
				/call CheckCasting
				/delay 5
			} else {
				/message \ay- I can not suspend my pet, dismissing it.
				/pet leave			
				/delay 5
			}
			|------------------------------
		}
		|----------------------------------
		/message ==================================================================
	}
	|-----------------------------

	/if (${Debugging}) /echo Sub CheckDriverPetStatus Exit
/return
| --------------------------------------------------------------------------------------------


| --------------------------------------------------------------------------------------------
| SUB: CheckMesh  ( Called from CheckThings )
| --------------------------------------------------------------------------------------------
Sub CheckMesh
	/if (${Debugging}) /echo Sub CheckMesh Entry
	/if (!${Navigation.MeshLoaded}) {
		/nav reload
		/delay 3s ${Navigation.MeshLoaded}
		/if (!${Navigation.MeshLoaded}) {
			/message \arNo navigational mesh could be found for this zone. Make one and try again.
			/varset Endmac TRUE
		}
	}
	/if (${Debugging}) /echo Sub CheckMesh Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckPlugin
| --------------------------------------------------------------------------------------------
  Sub CheckPlugin(string pluginname)
  /if (${Debugging}) /echo Sub CheckPlugin Entry

	|------------
	/if (!${Bool[${Plugin[${pluginname}]}]} && !${pluginname.Equal[E3BCS]}) {
		/message \ag${pluginname}\ax \arNOT\ax detected! This macro requires it! Loading ...
		/squelch /plugin ${pluginname}
		/if (!${Bool[${Plugin[${pluginname}]}]}) {
			/message \ag${pluginname}\ax \arSTILL NOT\ax detected! This macro requires it! EXITING ...
			/endmacro
		} else {
		    /message \ag${pluginname}\ax \atNOW\ax detected !
		}
	} else {
		/message \ag${pluginname}\ax detected!
	}
	|------------

	/if (${Debugging}) /echo Sub CheckPlugin Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: AutoSell_Loot_SupplyAgent
| --------------------------------------------------------------------------------------------
  Sub AutoSell_Loot_SupplyAgent
  /if (${Debugging}) /echo Sub AutoSell_Loot_SupplyAgent Entry

	/declare MerchName	string	local Merchant

	/message \aw<\ar$\ao$\ay$\ag$\at$\au$\am$\ap$\aw> \agAttempting to locate a \ay[\at${MerchName}\ay]\ag to \ay[\atAutoSell\ay]\ag ! \aw<\ap$\am$\au$\at$\ag$\ay$\ao$\ar$\aw>
	/target clear
	/delay 2s !${Target.ID}

	/squelch /target ${MerchName}
	/delay 2s ${Target.ID}

	|-------------------------------------
	/if (${Target.ID}) {
		/squelch /nav id ${Target.ID}
		/delay 5
		/while (${Navigation.Active}) {
			/call SetLoc
			/call CheckStuck
			/delay 5
		}
	}
	/delay 5
	|-------------------------------------

	|------------------
	/if (${ReclaimDC}) /call ReclaimAltDC
	|------------------

	|-------------------------------------
	/if (${Target.ID} && ${Target.Distance}<=20) {
		/nomodkey /click right target
		/delay 5s ${Window[MerchantWnd].Open}
		/message \ay Attempting to \amAutoSell\ax now.
		/delay 1s
		/call OpenPacks
		/delay 1s
		/autosell
		|-----------------
		/while (${Window[MerchantWnd].Open}) {
			/delay 5
		}
		|-----------------
		/call ClosePacks
		/delay 1s
	}
	|-------------------------------------

	/message \aw<\ar$\ao$\ay$\ag$\at$\au$\am$\ap$\aw> \agDone Selling! \ag \aw<\ap$\am$\au$\at$\ag$\ay$\ao$\ar$\aw>

	/if (${Debugging}) /echo Sub AutoSell_Loot_SupplyAgent Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: AutoSell_Loot
| --------------------------------------------------------------------------------------------
  Sub AutoSell_Loot
  /if (${Debugging}) /echo Sub AutoSell_Loot Entry

  	|--------------------------
	/message \am<***> Sending the rest of my group to Magus as I sell <***>
  	/squelch /e3bcgz /tar Magus Alaria
	/delay 5
	/squelch /e3bcgz /nav target
	/delay 5
	|--------------------------

	/declare MerchName	string	local Merabo

	/message \aw<\ar$\ao$\ay$\ag$\at$\au$\am$\ap$\aw> \agAttempting to locate a \ay[\at${MerchName}\ay]\ag to \ay[\atAutoSell\ay]\ag ! \aw<\ap$\am$\au$\at$\ag$\ay$\ao$\ar$\aw>
	/target clear
	/delay 2s !${Target.ID}

	/squelch /target ${MerchName}
	/delay 2s ${Target.ID}

	|-------------------------------------
	/if (${Target.ID}) {
		/squelch /nav id ${Target.ID}
		/delay 5
		/while (${Navigation.Active}) {
			/call SetLoc
			/call CheckStuck
			/delay 5
		}
	}
	/delay 5
	|-------------------------------------

	|------------------
	/if (${ReclaimDC}) /call ReclaimAltDC
	|------------------

	|-------------------------------------
	/if (${Target.ID} && ${Target.Distance}<=20) {
		/nomodkey /click right target
		/delay 5s ${Window[MerchantWnd].Open}
		/message \ay Attempting to \amAutoSell\ax now.
		/delay 1s
		/call OpenPacks
		/delay 1s
		/autosell
		|-----------------
		/while (${Window[MerchantWnd].Open}) {
			/delay 5
		}
		|-----------------
		/call ClosePacks
		/delay 1s
	}
	|-------------------------------------

	/message \aw<\ar$\ao$\ay$\ag$\at$\au$\am$\ap$\aw> \agDone Selling! \ag \aw<\ap$\am$\au$\at$\ag$\ay$\ao$\ar$\aw>

	/if (${Debugging}) /echo Sub AutoSell_Loot Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: ReclaimAltDC
| --------------------------------------------------------------------------------------------
Sub ReclaimAltDC
 /if (${Debugging}) /echo Sub ReclaimAltDC Entry

	/varset CurrentDC ${FindItemCount[=Diamond Coin]}
	/varset CurrentDCAC ${Me.AltCurrency[20]}
	
	/message ==================================================================
	/message \ayDiamond Coin: Alternate Currency=(\at${CurrentDCAC}\ay) | Inventory=(\at${CurrentDC}\ax)

	|-----------------------------------------------
	/if (${CurrentDC}>0) {
		; --- If I have DC in inventory, RECLAIM it to Alternate Currency !!!
		/message \ag$$$\ay I have [\atDiamond Coin\ay]  to reclaim!\ax

		; Open the Inventory Window if it is closed
		|----------------------------------------------
		/if (!${Window[InventoryWindow].Open}) /call OpenInvWindow
		|----------------------------------------------

		; Select Alt Currency Tab
		/if (${Debugging}) /echo Selecting Alt Currency Tab
		/if (!${Window[InventoryWindow].Child[IW_AltCurrPage].Open})  /notify InventoryWindow IW_Subwindows tabselect 5
		/delay 5

		; Select Diamond Coin off the Alternate Currecy tab in Inventory window ..  YOU NEED TO OPEN INVENTORY WINDOW FOR THIS !
		/if (${Debugging}) /echo Selecting Diamond Coins
		/notify InventoryWindow IW_AltCurr_PointList listselect 2
		/delay 5

		; Click the RECLAIM BUTTON after selecting Diamond Coin previously
		/nomodkey /notify InventoryWindow AltCurr_ReclaimButton LeftMouseUp
		/delay 5
	} else {
	    ; --- If I have NO DC in inventory to RECLAIM
		/message \ag$$$\ay I have \arNO\ay [\atDiamond Coin\ay] to reclaim!\ax
	}
	|-----------------------------------------------
	; Update the DC and Alternate DC Currency ammount.
	/varset CurrentDC ${FindItemCount[=Diamond Coin]}
	/varset CurrentDCAC ${Me.AltCurrency[20]}
	/message \ayDiamond Coin: Alternate Currency=(\at${CurrentDCAC}\ay) | Inventory=(\at${CurrentDC}\ax)
	/message ==================================================================
	; Close the Inventory Window if it is open
	|----------------------------------------------
	/if (${Window[InventoryWindow].Open}) /call CloseInvWindow
	|----------------------------------------------

	/if (${CurrentDC}==0) /message \ag$$$ \ayAll available DC was converted to Alternate Currency !

/if (${Debugging}) /echo Sub ReclaimAltDC Exit

/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: OpenInvWindow
| --------------------------------------------------------------------------------------------
  Sub OpenInvWindow
 /if (${Debugging}) /echo Sub OpenInvWindow Entry
	/if (!${Window[InventoryWindow].Open}) {
	:OpenInventoryWindow
		/nomodkey /keypress inventory
		/delay 5
		/if (${Window[InventoryWindow].Open}) /message Inventory Window (Open).
		/if (!${Window[InventoryWindow].Open}) /goto :OpenInventoryWindow
	}
 /if (${Debugging}) /echo Sub OpenInvWindow Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: CloseInvWindow
| --------------------------------------------------------------------------------------------
  Sub CloseInvWindow
  /if (${Debugging}) /echo Sub CloseInvWindow Entry

	/if (${Window[InventoryWindow].Open}) {
	:CloseInventoryWindow
		/nomodkey /keypress inventory
		/delay 5
		/if (!${Window[InventoryWindow].Open}) /message Inventory Window (Closed).
		/if (${Window[InventoryWindow].Open}) /goto :CloseInventoryWindow
	}

  /if (${Debugging}) /echo Sub CloseInvWindow Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: CheckIfBagsFull
| --------------------------------------------------------------------------------------------
  Sub CheckIfBagsFull
  /if (${Debugging}) /echo Sub CheckIfBagsFull Entry

  |--------------------------------------------
  /if (${BagsAreFull}) {
		|--------------------------------------------
		/if (${Me.AltAbilityReady[Summon Resupply Agent]}) {
			/message ==================================================================
			/message \ar +++ Your bags are full summoning a \ay[\atResupply Agent\ay]\ar to AutoSell.\ax
			/message ==================================================================
			/alt act ${Me.AltAbility[Summon Resupply Agent].ID}
			/delay 2s
			/call AutoSell_Loot_SupplyAgent
			/delay 1s
		} else {
			message ==================================================================
			/message \ar +++ Your bags are full and you can not summon a \ay[\atResupply Agent\ay]\ar to AutoSell.\ax
			/message \ar --- DISABLING ${MacroName} LOOTING, YOU WILL NOT LOOT CORPSES !
			/message ==================================================================
			/squelch /lootoff
		}
		|--------------------------------------------
		/varset BagsAreFull FALSE
		|--------------------------------------------
  }
  |--------------------------------------------

  /if (${Debugging}) /echo Sub CheckIfBagsFull Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SECTION: -- Events   --   START
| --------------------------------------------------------------------------------------------
|--------------------------------------------------------
Sub Event_Cannot_See
	/stick off
	/delay 30
	/squelch /call WaitNav ${Target}
	/delay 5
	/stick
	/doevents flush Cannot_See
/return
|--------------------------------------------------------
|--------------------------------------------------------
Sub Event_Cant_Hit
	/stick off
	/delay 30
	/squelch /call WaitNav ${Target}
	/delay 5
	/stick
	/doevents flush Cant_Hit
/return
|--------------------------------------------------------
|--------------------------------------------------------
Sub Event_Too_Far
	/stick off
	/delay 30
	/squelch /call WaitNav ${Target}
	/delay 5
	/stick
	/doevents flush Too_Far
/return
|--------------------------------------------------------
|--------------------------------------------------------
  Sub Event_NavMeshReload
	/message \agReloading navmesh for zone: \ay(\am${Zone.Name}\ay)\ag on all toons.
	/squelch /e3bcgza /nav reload
	/call BackUp
	/delay 1s
    /doevents flush NavMeshReload
  /return  
|-------------------------------------------------------- 
|--------------------------------------------------------
  Sub Event_NavMeshReload
	/message \agReloading navmesh for zone: \ay(\am${Zone.Name}\ay)\ag on all toons.
	/squelch /e3bcgza /nav reload
	/call BackUp
	/delay 1s
    /doevents flush NavMeshReload
  /return  
|-------------------------------------------------------- 
|--------------------------------------------------------
Sub Event_TurboLootDone
	/message \at+ \am[\ag${TurboLooter}\am]\ay has finished looting.
	/varset TurboLootPause FALSE
	/doevents flush TurboLootDone
/return
|-------------------------------------------------------
|--------------------------------------------------------
Sub Event_BagsFull
	/varset BagsAreFull TRUE
	/doevents flush BagsFull
/return
|--------------------------------------------------------
| --------------------------------------------------------------------------------------------
| SECTION: -- Events   --   END
| --------------------------------------------------------------------------------------------
